### ISSUE TITLE
Keyboard binding for moving between popup options 

### ISSUE THREAD

**Issue by fluteguitar** [jacktasia/dumb-jump#100]
Could you please add key binding for ```select```, ```go-back-ward```, and ```go-forward``` for picking destination to jump when the popup suggestion tooltip is displayed?

![image](https://cloud.githubusercontent.com/assets/10528635/22877043/29022920-f206-11e6-89e7-252b85868570.png)

Thanks.

**Comment by jacktasia** [comment]
If you already have helm or ivy installed then you can use those instead of the popup, which have much better options available.

`(setq dumb-jump-selector 'ivy)`
`(setq dumb-jump-selector 'helm)`

**Comment by fluteguitar** [comment]
Hi @jacktasia,
Thank for the suggestion. I would play with them.
