### ISSUE TITLE
Implement jumping to matches not in current file

### ISSUE THREAD

**Issue by netromdk** [jacktasia/dumb-jump#104]
In some cases, you want to jump to an external definition, but there are local uses in the current file that you don't want it to match at all.

Perhaps adding `dumb-jump-go-non-current` and `dumb-jump-go-non-current-other-window` interactive functions for this purpose?

Thanks

**Comment by netromdk** [comment]
Or it could sort matches for current file last, so it still jumps locally if no external matches are found.

**Comment by jacktasia** [comment]
I agree that this is a good idea. I think I like `dumb-jump-go-prefer-external` and `dumb-jump-go-prefer-external-other-window` best.
