### ISSUE TITLE
dumb-jump not found

### ISSUE THREAD

**Issue by bucketzxm** [jacktasia/dumb-jump#105]
Hi, 
  I am using packing-install to install the dump-jump, but it shows ~~dump-jump~~(was a typo)dumb-jump not found. 
The original message is : 
`https://melpa.org/packages/dumb-jump-20161218.110.el: Not found` 

Any Ideas ? 

Thanks

**Comment by netromdk** [comment]
It's called `dumb-jump`. :)

**Comment by bucketzxm** [comment]
sorry.. I made a mistake when creating the issue.. ... i typed the 'dumb-jump' in emacs actually ..

**Comment by bucketzxm** [comment]
it works ! Thank you !
