### ISSUE TITLE
Ruby support?

### ISSUE THREAD

**Issue by Silex** [jacktasia/dumb-jump#12]
Hello,

how difficult would it be to support Ruby? maybe simply copy-paste adapt python support?

**Comment by jacktasia** [comment]
> how difficult would it be to support Ruby?

Theoretically, it should be pretty easy.

> maybe simply copy-paste adapt python support?

Yeah, this is probably how I would start. Now that there's interest in Ruby I will look at the popular Ruby repos on GitHub and see what I can get working tonight after work.

Thanks for bringing this up!

**Comment by Silex** [comment]
Fantastic :+1:  Thanks!
