### ISSUE TITLE
Jumping vs. showing candidates

### ISSUE THREAD

**Issue by netromdk** [jacktasia/dumb-jump#122]
In `dumb-jump-handle-results` there's a `do-var-jump` that I find a little flawed. Especially the `(string= ctx-type "")` part from my excerpt beneath:

```elisp
(matches
 (if (not prefer-external)
     (-distinct
      (append (dumb-jump-current-file-results cur-file match-cur-file-front)
              (dumb-jump-current-file-results rel-cur-file match-cur-file-front)))
   match-cur-file-front))

(var-to-jump (car matches))

(do-var-jump (and (or (= (length matches) 1)
                      (string= ctx-type "variable")
                      (string= ctx-type ""))
                  var-to-jump))
```

Before I fixed the absolute/relative current file matching in https://github.com/jacktasia/dumb-jump/commit/e23bff8b918c41dd8dc9a13cc117e919bd21e58a it would not trigger `do-var-jump` because `matches` wouldn't get a size of 1 often. However, now, if there is one match or the `ctx-type` is `""` then it just jumps. In most situations I only want it to show me the candidates to select from - if there is only one candidate at all, then it's fine that it just jumps.

I think you jump when context is empty due to some of the tests perhaps?
Hope it makes sense.

**Comment by netromdk** [comment]
Another perspective: Let's say there are three matches, one in the current file, and two in other files. I typically don't want to jump in the same file when there are multiple matches. Sometimes it's fine but other times it isn't. In the cases where it just jumps incorrectly, let's say, then you can't get an overview of all candidates either, which I personally find very useful - and it's why I like the overview more than just blindly jumping.

**Comment by jacktasia** [comment]
> it would not trigger do-var-jump because matches wouldn't get a size of 1 often

I suppose this is more a function of the code base you're jumping within. For example, in my projects I almost always get one match and an immediate jump. That hasn't ever changed for me.

> I think you jump when context is empty due to some of the tests perhaps?

I honestly can't remember 100%, but I am pretty sure my thinking was if it's a `variable` context match then it makes sense to jump to the first/closest match. For example, think of a project where `users` is a local variable in almost every file/function. The `""` support was purely to support those languages that did not have any contexts defined. Obviously not perfect and I was at an advantage since I would just add contexts for the languages I used most 😉 

> In the cases where it just jumps incorrectly, let's say, then you can't get an overview of all candidates either, which I personally find very useful - and it's why I like the overview more than just blindly jumping.

I see where you're coming from and I am supportive of making a change where we're less aggressive about jumping and potentially adding another config like `dumb-jump-aggressive` that is `t` or `nil`.

**Comment by netromdk** [comment]
> I suppose this is more a function of the code base you're jumping within. For example, in my projects I almost always get one match and an immediate jump. That hasn't ever changed for me.

I understand it different from user to user. But for me, working with rather huge C++ projects, the definitions are almost always not in the same file. And personally, if they were in the same file I would probably just <kbd>C-s</kbd> for it anyway.

> I honestly can't remember 100%, but I am pretty sure my thinking was [...]

Sure, I understand. 😁 

It would be great with a way to tweak Dumb Jump to do one or the other thing discussed here. If `dumb-jump-aggressive` is created then I guess it just default to aggressive because it's kind of the default now? And it would simply mean that if no context is defined then it doesn't `do-var-jump` if `(setq dumb-jump-aggressive nil)`?

**Comment by jacktasia** [comment]
First of all thanks for opening this issue. I forgot to say that before.


> It would be great with a way to tweak Dumb Jump to do one or the other thing discussed here.

I agree and I am totally open to anything you'd like to PR.

> If dumb-jump-aggressive is created then I guess it just default to aggressive because it's kind of the default now? And it would simply mean that if no context is defined then it doesn't do-var-jump if (setq dumb-jump-aggressive nil)?

Yeah, I think so. It should be a simple as:

```
(do-var-jump
 (and 
  (or (= (length matches) 1)
      (and 
       dumb-jump-aggressive
       (or
        (string= ctx-type "variable")
        (string= ctx-type ""))))
  var-to-jump))
```

with 

```
(defcustom dumb-jump-aggressive
  t
  "If `t` jump aggressively with the possiblity of a false positive. if nil always show list of more than 1 match"
  :group 'dumb-jump
  :type 'boolean)
```

but correct me if I am wrong.

**Comment by netromdk** [comment]
I was more thinking like this:
```el
(do-var-jump
 (and (= (length matches) 1)
      (or (string= ctx-type "variable")
          dumb-jump-aggressive)
      var-to-jump))
```

Meaning if there is one match (in current file) and context is "variable", aggressive or not, then it would jump. In aggressive mode it would just ignore the context?

**Comment by netromdk** [comment]
Otherwise it could be determine directly with the aggressive mode:
```el
(do-var-jump
 (and dumb-jump-aggressive
      (or (= (length matches) 1)
          (string= ctx-type "variable")
          (string= ctx-type ""))
      var-to-jump))
```

**Comment by jacktasia** [comment]
I _think_ your first way would be more aggressive than it currently is (for `function` contexts) and your second way would never cause the jump if you only had one match unless you had aggressive mode on.

**Comment by netromdk** [comment]
It's not working for me if `(= (length matches) 1)` makes it jump because I have files with one match in the current file and several externally where I don't want it to jump inside the current file. So maybe non-aggressive means it will not jump if there is one match in current file and one or more in `match-cur-file-front` in general?

Like this:
```el
(do-var-jump
 (and (or dumb-jump-aggressive
          (= (length match-cur-file-front) 1))
      (or (= (length matches) 1)
          (string= ctx-type "variable")
          (string= ctx-type ""))
      var-to-jump))
```

**Comment by jacktasia** [comment]
> So maybe non-aggressive means it will not jump if there is one match in current file and one or more in match-cur-file-front in general?

Yeah, I mean my thinking was if it's the non-aggressive mode then it would only ever automatically jump if there was only 1 place (overall, regardless of files) to jump to. (my code example was probably out of date)

**Comment by netromdk** [comment]
That's great. Then we agree. 👍 I'll make a PR now.
