### ISSUE TITLE
Independent of underlying shell?

### ISSUE THREAD

**Issue by indigoviolet** [jacktasia/dumb-jump#124]
I find that when I've enabled Iterm2's shell integration (https://www.iterm2.com/documentation-shell-integration.html), `dumb-jump` starts finding filenames like 

```
~/dir/dir/dir/^[]1337;RemoteHost=foobar@foobar-MacBook-Pro-2.local^G^[]1337;CurrentDir=/Users/foorbar/dir/dir^G^[]1337;ShellIntegrationVersion=5;shell=zsh^G/Users/foobar/dir/dir/dir/filename.rb
```

Wouldn't it be better if the dumb-jump commands ran in a shell that wasn't affected by these sorts of login customizations?

**Comment by jacktasia** [comment]
Thanks for report!

> Wouldn't it be better if the dumb-jump commands ran in a shell that wasn't affected by these sorts of login customizations?

Certainly seems that way. Although we're currently just using `shell-command-to-string` and after a very shallow 2 minutes of googling haven't seen any obvious alternatives, but I would think this would pretty easy to implement once I figure out what I should be using instead. I'll update this with any progress. Thanks again!

**Comment by netromdk** [comment]
`shell-command-to-string` uses `shell-file-name` to run the commands:
> shell-file-name is a variable defined in ‘C source code’.
Its value is "/bin/zsh"
Original value was "/bin/bash"

> Documentation:
File name to load inferior shells from.
Initialized from the SHELL environment variable, or to a system-dependent
default if SHELL is unset.  See Info node ‘(elisp)Security Considerations’.

**Comment by jacktasia** [comment]
@netromdk So it seems like we'd have to make a special version of `shell-command-to-string` for Dumb Jump that depending on the `shell-file-name` had its own version of `shell-command-switch` (which for `bash` defaults to `-c` but we would need it to be `--noprofile -c` and for `zsh` add `--no-rcs`) Thoughts on this route?

**Comment by indigoviolet** [comment]
@netromdk that was helpful, I think I was able to fix it by setting `shell-command-switch`

```
(setq shell-file-name "/bin/zsh")
(setq shell-command-switch "-icf")
```

**Comment by netromdk** [comment]
The difficult part is knowing the arguments to pass to the given shell to "use no profile". We could detect what value the variable has and temporarily use known arguments, like you mentioned @jacktasia. But I'd be more powerful with a generic solution somehow.

**Comment by netromdk** [comment]
There doesn't seem to be any good, generic solution so I'd vote for setting _temporary_ arguments given the shell defined in `shell-file-name`.

**Comment by jacktasia** [comment]
@netromdk Thanks for the notes!

> There doesn't seem to be any good, generic solution so I'd vote for setting temporary arguments given the shell defined in shell-file-name.

Agreed.  I think in the short-term we only support `bash` and `zsh` and then if there's like at least two `[`s per every searcher line then we warn the user and ask them to create an issue so we can (potentially) support whatever shell they're using. I am mainly worried about Windows and other systems I have little experience with.

That said, simply touching on this potential issue in the README with the manual fix examples for some shells may be enough, but as always, I'll happily take PRs.

**Comment by netromdk** [comment]
That's a great idea about warning people, but that warning must be possible to disable - like we can for emacs ones. 👍

**Comment by alphapapa** [comment]
Forgive the intrusion, just noticed this:

> I think in the short-term we only support bash and zsh and then if there's like at least two [s per every searcher line then we warn the user and ask them to create an issue so we can (potentially) support whatever shell they're using. 

Bash (and I think zsh also) explicitly supports the `[[ ... ]]` test syntax (in fact, it's far superior to the  `[ ... ]` syntax, and unless one is targeting plain `sh` or `dash`, should generally be used instead).

**Comment by jacktasia** [comment]
> Bash (and I think zsh also) explicitly supports the [[ ... ]] test syntax (in fact, it's far superior to the [ ... ] syntax, and unless one is targeting plain sh or dash, should generally be used instead).

@alphapapa  My point was that if there's multiple `[` on every searcher response line then that probably means that color codes have found their way into the shell somehow. So this would be on the emacs lisp parsing side not the command running side.

**Comment by alphapapa** [comment]
Ah, good point.  :)
