### ISSUE TITLE
Make it easier to debug dumb-jump's behavior

### ISSUE THREAD

**Issue by cweiske** [jacktasia/dumb-jump#127]
I'm using dump-jump in a new PHP project and only get an error message:
> 'AdditionalFieldProviderInterface' php  declaration not found.

I've added a `.dumbjumpignore` file to my extension to make d-j search more files, but dumb-jump still does not find the file.
To debug this problem, I have to edit the d-j sources and restart emacs.

It would be helpful if I could

1. print the current project root with a command
2. see the command used to search without editing the dumb-jump sources

**Comment by netromdk** [comment]
FYI: You don't have to restart emacs you can just `eval-buffer` or region.

**Comment by netromdk** [comment]
I normally uncomment [here](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L1426) and look at what it prints. But it would be nice with some better debugging facilities.

**Comment by jacktasia** [comment]
I just added a `dumb-jump-debug` config var to optionally output _some_ helpful debug information. I think there's more we'd probably want to output when it's on. 

Turn it on with `(setq dumb-jump-debug t)`
