### ISSUE TITLE
Multi-line patterns

### ISSUE THREAD

**Issue by rompy** [jacktasia/dumb-jump#129]
`dumb-jump` will fail for anything else except `ag` in this case:
```
int main(
    int argc,
    char **argv
    )
{
    return 0;
}
```

Apparently `rg` and `git grep` doesn't support multi-line patterns, and `gnu grep` supports them with `-E -z -o` arguments only.

You should mention that in the README, so others won't spend time debugging this 😄

**Comment by jacktasia** [comment]
Thanks for the report. I agree this should be mentioned somewhere.
