### ISSUE TITLE
ag: unrecognized option '--vimgrep'

### ISSUE THREAD

**Issue by Silex** [jacktasia/dumb-jump#13]
Hello,

I'm curious about why you call `ag` directly instead of leveraging https://github.com/Wilfred/ag.el ?

Anyway, I suffer from the same bug as https://github.com/Wilfred/ag.el/commit/cd8931997989c5401a153e028bac4bd14ca27f6e

Namely that the default `ag` installation on ubuntu doesn't support `--vimgrep`.

Maybe it's too much work to rewrite using `ag.el`, in which case I'll upgrade my ag installation but I thought you'd like to know.

**Comment by jacktasia** [comment]
Thanks for reporting this! I wrongly assumed that `--vimgrep` wasn't a recent addition. I will look into adding support for `ag` installations that do not have `--vimgrep` tonight either via `ag.el` or `--nocolor`...and at the very least warn the user to upgrade their `ag`.

Thanks again.

**Comment by Silex** [comment]
:+1:
