### ISSUE TITLE
Jumping to `defvar' in the same file in .el files

### ISSUE THREAD

**Issue by srustamo** [jacktasia/dumb-jump#130]
I'm not so sure (and the docs are not clear on this) how calling `dumb-jump-go` in in an .el file behaves.

Say, this is a a file:
```
1 (defvar emacs-d
2 (file-name-directory
3   load-file-name))

4 (setq package-user-dir
5      (expand-file-name "elpa" emacs-d))
```
Say, I'm on line 5, point is on `emacs-d` symbol and run `dumb-jump-go`. 

What I get is (without .dumbjump and if the dir contains many files) `Took over 2s to find ’emacs-d’. Please install ag or rg, or add a .dumbjump file to ’/Users/xx3’ with path exclusions`.

So, it looks like line 1 defvar is not found.

**Comment by jacktasia** [comment]
Your example works fine for me. Looks like your operating out of your home directory, or a directory with nothing to denote its project root (so it's defaulting to `~`), and dumb-jump is going to search all child directories recursively. I recommend you look at this issue: https://github.com/jacktasia/dumb-jump/issues/128

**Comment by srustamo** [comment]
I freshly clone [this](https://github.com/srustamo/rush-emacs) repo, and open `init.el` in the root and do `dumb-jump-go` on line [18](https://github.com/srustamo/rush-emacs/blob/master/init.el#L18) of the file (which is what the opening issue was about), and still get  this subject error.

GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
 of 2017-04-26

**Comment by srustamo** [comment]
Incidentally, the this package functions work fine on a C project, other things being equal.

**Comment by jacktasia** [comment]
Thanks for the example. Your `rush-emacs` project has a `.gitignore` of just `*`. Most searchers (like `ag`) respect the `.gitignore` file and do not search anything that matches it.  If you remove the full wildcard `*` then dumb-jump works as expected.

https://github.com/srustamo/rush-emacs/blob/master/.gitignore

**Comment by srustamo** [comment]
Thank you.
