### ISSUE TITLE
open in existing window if file already visible

### ISSUE THREAD

**Issue by wbolster** [jacktasia/dumb-jump#131]
it would be great if `dumb-jump` could jump to a definition, and if the file containing that definition is already shown in another window (e.g. split view), it would just reposition and focus that window.

right now it's either the current window or "other window", but there is a sensible middle ground that seems impossible right now.

**Comment by wbolster** [comment]
i can come up with a pr that implements this, so please let me know whether you think this is a good feature to have. (i obviously want it.)

**Comment by wbolster** [comment]
``` elisp
(defcustom dumb-jump-use-existing-window
  t
  "Whether to jump into the existing window if the target file is already visible."
  :group 'dumb-jump
  :type 'boolean)
```

is the approach i would like

**Comment by wbolster** [comment]
```
-  (if (eq dumb-jump-window 'other)
-      (find-file-other-window thefile)
-    (unless (string= thefile (buffer-file-name))
-      (find-file thefile)))
+  (let* ((buffer (find-buffer-visiting thefile))
+         (window (when buffer (get-buffer-window buffer))))
+    (cond
+     ((and window dumb-jump-use-existing-window)
+      (select-window window))
+     ((eq dumb-jump-window 'other)
+      (find-file-other-window thefile))
+     (t (find-file thefile))))
+
```

and this is how it would work. ;)

anyway, let me know what you think, and i will submit a proper pr.

**Comment by jacktasia** [comment]
I think this is a great idea and I'd happily take the PR. Thanks!

**Comment by wbolster** [comment]
ok you can assign this issue to me. i will probably polish it a bit to make it work sensibly with multiple frames as well.
