### ISSUE TITLE
Prompt for symbol

### ISSUE THREAD

**Issue by pesterhazy** [jacktasia/dumb-jump#133]
Thanks for this gem!

One useful enhancement would be to prompt for a function name (sybol) instead of using the symbol-at-point. I find myself using helm-ag a lot to find a specific function in my project even if it's not currently under the cursor. `dumb-jump`'s algorithm would work much better because it filters out non-definitions.

**Comment by jacktasia** [comment]
Thanks for opening this issue. I totally agree. I think I have this working in #134 if you have any feedback. If not, I just want to do some more tests and then I'll merge it in a day or two. Thanks again!

**Comment by jacktasia** [comment]
The version of dumb-jump with the new `dumb-jump-go-prompt` interactive command is now available on MELPA. The README has also been updated. Thanks again for the suggestion!

**Comment by pesterhazy** [comment]
Just tried it, it works great! Thanks so much!

**Comment by jacktasia** [comment]
> Just tried it, it works great! Thanks so much!

Thanks for the feedback. Glad to hear it!
