### ISSUE TITLE
external lib paths with a git repo

### ISSUE THREAD

**Issue by kubaroth** [jacktasia/dumb-jump#140]
How does at the moment the external libraries are handled within a git repo? If I put a .dumbjump file (with external paths specified) at the same level as .git it seem the former one is not taken into account.

**Comment by jacktasia** [comment]
It should be looking for a `.dumbjump` file first. As far as I know this works as expected, but obviously, a bug is possible. Please provide more details. If the repo in question is publically available a link would be great, but if it's private if you could provide as much detail as possible for me to potentially reproduce your issue, like:

* programming language of your project
* the contents of your `.dumbjump` file (feel free to sanitize any paths)
* the directory structure of your project
* anything else you're willing to provide.

Thanks!

**Comment by kubaroth** [comment]
Thanks for quick reply.
This is python and I have a single entry in the .dumbjump which point to the root level of the external library.
Update: Temporarily renaming .git solves my problem.

**Comment by kubaroth** [comment]
Wondering if you had any luck reproducing it? I have a limited bandwith at the moment and workarouned the problem by returning nil instead of ` ;; (f-exists? (f-join proj-root ".git"))`. Feel free to close it if it works for you.

**Comment by jacktasia** [comment]
> workaround the problem by returning nil instead of ;; (f-exists? (f-join proj-root ".git")). 

Oh! Thanks for mentioning this! I see what's happening now. When we changed to defaulting to `git-grep` if there's a `.git` in the project root that would break searching outside the repo (with a `.dumbjump` config) since `git-grep` almost certainly doesn't support searching outside its own repo.

Easiest fix for now would be to force `ag` or `rg` in your `~/.emacs` like this: `(setq dumb-jump-force-searcher 'ag)`

@netromdk Thoughts?

**Comment by kubaroth** [comment]
Thanks, I can confirm forcing in ~/.emacs does work with 'rg but does not with 'grep. I get a message "python  declaration not found."

**Comment by jacktasia** [comment]
> Thanks, I can confirm forcing in ~/.emacs does work with 'rg but does not with 'grep. I get a message "python declaration not found."

Great, thanks for confirming! I'll plan on updating the code to not allow defaulting to `git-grep` when an outside path is added to the `.dumbjump` and in the short-term, I will update the README docs on `.dumbjump` with a warning about this issue. Thanks again!

**Comment by kubaroth** [comment]
Thanks, great tool btw!
