### ISSUE TITLE
Failing to use the fallback major-mode detection for shell-scripts without extension

### ISSUE THREAD

**Issue by terlar** [jacktasia/dumb-jump#144]
When I try to use dumb-jump inside an extensionless shell-script file I want it to fallback on the major-mode detection. But somehow it doesn't enter that case, instead says: `Could not find rules for '.? file'.`

If I manually run `(dumb-jump-get-language (buffer-file-name))` it will return `".? file"`. So it is not that strange. But the curious thing is:

- `(dumb-jump-get-language-by-filename (buffer-file-name))` returns `nil`
- `(dumb-jump-get-language-from-mode)` returns `"sh"`

And looking at the function definition for `dumb-jump-get-language` I can't understand why it doesn't fall-back to the mode-line but instead ends up with this question-mark file extension.

**Comment by terlar** [comment]
Having a second look at this it is pretty clear what is wrong here, it is because the major-mode for `shell` is `sh-mode` and the `dumb-jump-find-rules` only has `shell` defined. So perhaps add `sh` in there to support this?

**Comment by jacktasia** [comment]
Thanks for reporting this! There's a new version up on MELPA that should have this fixed.

**Comment by terlar** [comment]
Now the mode triggers properly, but doesn't seem to be able to look up things properly.

Try this simple script, name it `demo` for creativity:

```bash
#!/usr/bin/env bash
[[ "${TRACE}" ]] && set -x
set -euo pipefail

findme() {
	echo Another function
}

main() {
	findme
}

main "$@"
```

If you have your cursor on `findme` function call and execute the `dumb-jump-go`. Then you will get the result: `'findme' shell  declaration not found.`

**Comment by jacktasia** [comment]
Your example worked for me. Can you provide more details?

* Searcher (git-grep, ag, rg, grep)
* Set `(setq dumb-jump-debug t)` and try search and copy/paste `*Messages*` results
* Emacs version
* OS/shell

Thanks!

**Comment by terlar** [comment]
Interesting... It seems it is searching in the wrong folder somehow.

I open a file in `/home/terje/test` but somehow the search is done inside `/home/terje/.emacs.d`.

- Searcher: `rg`
- Emacs version: `GNU Emacs 25.2.1`
- OS: Linux 4.11.3-1-ARCH

```
-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----- 

cmd: 
	rg --color never --no-heading --line-number function\\s\*findme\\s\*\|findme\\\(\\\)\\s\*\\\{\|\\bfindme\\s\*\=\\s\* /home/terje/.emacs.d

raw results: 

	 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ (FALLBACK!) START
----- 

cmd: 
	rg --color never --no-heading --line-number \\bfindme\(\$\|\[\^\\w-\]\) /home/terje/.emacs.d

raw results: 
	 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ (FALLBACK) END
-----

’findme’ shell  declaration not found.
```

I am using persp-mode and projectile, could they be interfering?

**Comment by terlar** [comment]
Once again might be my fault, it is not that strange, I have put my default project as my emacs directory, which explains the behavior, so in this case I guess it is correct but confusing. The problem was the other time where I actually had a project open, but then I guess it didn't manage to identify that and used the default project as well. Just strange that it worked before this change, that is what got me confused.

**Comment by jacktasia** [comment]
Thanks for the debug info. I am glad you got it working. Please let me know if you have any ideas on how the documentation could be better.

**Comment by terlar** [comment]
I didn't really get it working though, since it is still searching the wrong directory. I just know that that is the issue now. Not sure why it doesn't find the directory but instead falls back to the default project.

**Comment by jacktasia** [comment]
Check out #128  it's falling back to the default project because it can't detect one.

**Comment by terlar** [comment]
This is the output from when I am in an actual project, so my "isolated" test was having the wrong preconditions.

```
-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----- 

cmd: 
	git grep --color=never --line-number --untracked -E function\\s\*has_xdotool\\s\*\|has_xdotool\\\(\\\)\\s\*\\\{\|\\bhas_xdotool\\s\*\=\\s\* -- /home/terje/src/github.com/terlar/dotfiles/\*.sh /home/terje/src/github.com/terlar/dotfiles/\*.bash /home/terje/src/github.com/terlar/dotfiles/\*.csh /home/terje/src/github.com/terlar/dotfiles/\*.ksh /home/terje/src/github.com/terlar/dotfiles/\*.tcsh

raw results: 

	 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ (FALLBACK!) START
----- 

cmd: 
	git grep --color=never --line-number --untracked -E \\bhas_xdotool\(\$\|\[\^\\w-\]\) -- /home/terje/src/github.com/terlar/dotfiles/\*.sh /home/terje/src/github.com/terlar/dotfiles/\*.bash /home/terje/src/github.com/terlar/dotfiles/\*.csh /home/terje/src/github.com/terlar/dotfiles/\*.ksh /home/terje/src/github.com/terlar/dotfiles/\*.tcsh

raw results: 
	 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ (FALLBACK) END
-----

’has_xdotool’ shell  declaration not found.
```

Seems the filter explicitly searches for files with extensions, so it won't work for these unnamed shebang scripts.

**Comment by terlar** [comment]
So in this case it is using `git grep` and detects the project correctly but is too explicit in the search pattern.

**Comment by jacktasia** [comment]
Try restarting your emacs.

**Comment by terlar** [comment]
I have restarted `emacs` and tried both in server-mode (also restarted) which I usually run, but also in a fresh new client. Do you think the wrong code is run? Could there be some cache somewhere or that it hasn't redone the byte-compilation since I updated the package?

Thank you for your support, feedback and great tool.

**Comment by jacktasia** [comment]
>  Do you think the wrong code is run? 

The generated searcher command shouldn't have explicitly listed the shell file extensions because I removed them in [this commit](https://github.com/jacktasia/dumb-jump/commit/9743f3f2736c0e84c5dff860a142c78a0c4ed861#diff-7d5fde248d17c1592b9a27209496fe24R838). As you mentioned this is an important element of supporting extension-less shell scripts.

> Could there be some cache somewhere or that it hasn't redone the byte-compilation since I updated the package?

This is why I suggested restarting but can't say for sure. Can you try setting `dumb-jump-force-searcher` to `ag` or `rg`?

> Thank you for your support, feedback and great tool.

Sure thing :smile:

**Comment by terlar** [comment]
It is "working" with `rg`, or it would be working, the only problem is that in this file, in this specific project the file lives in a hidden directory, so by default it is filtered out by `rg` but if I put it anywhere else it works.

**Comment by terlar** [comment]
So the working one with `rg` looks something like this:

```
-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----- 

cmd: 
	rg --color never --no-heading --line-number function\\s\*ssh\:\:command\\s\*\|ssh\:\:command\\\(\\\)\\s\*\\\{\|\\bssh\:\:command\\s\*\=\\s\* /home/terje/src/github.com/company/tools

raw results: 

	/home/terje/src/github.com/company/tools/bin/spl-ec2:46:ssh::command() {
 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----
```

**Comment by jacktasia** [comment]
Thanks for the debug output. Fixed `git-grep` so it won't limit to a certain set of file extensions if searching from an extensionless file. It may be a few hours before MELPA picks up the change.

**Comment by terlar** [comment]
Perfect! It is working now. Would it be possible to either have a toggle to let rg search through hidden files with a toggled variable and also be able to control the ignore list could be a great addition. Alternatively some way to inject option switches that will be given to the command.

Right now `git-grep` works, but if I have a project with "hidden" directories, like my `dotfiles` it would not be searchable with the rg backend together with dumb-jump.

Personally when I use `rg`, I usually use it together with the options `rg --hidden --glob "!.git/*"`.

This might however be a different issue, so I guess you can close this one. Thanks for the quick fix :+1: .
