### ISSUE TITLE
add a global variable `dumb-jump-project`

### ISSUE THREAD

**Issue by redguardtoo** [jacktasia/dumb-jump#145]
The project I'm working on is using Perforce.

I prefer `dumb-jump-project` to override the automatic project detection or else my real project can never be found because my home directory is under git control.

**Comment by jacktasia** [comment]
Any reason `dumb-jump-default-project` wouldn't work?

**Comment by redguardtoo** [comment]
`/home/cb/.git` already exists. `/home/cb/projs/p4-project` is my perforce project.
Your code might use `locate-dominating-file` to find project root. So `/home/cb` is found because `.git` exists there. So `dumb-jump-default-project` doesn't have a chance.

My company has strict policy on security, so I want to avoid creating any `denoter` file or directory in case I accidentally commit the denoter.

**Comment by jacktasia** [comment]
Yeah, adding a `.dumbjump` file to your project would be the easiest solution, but since I feel so bad that you're forced to use Perforce I went ahead and added this: 8c78bf3

This will automatically be available via MELPA in a few hours.

**Comment by redguardtoo** [comment]
Great. Thanks
