### ISSUE TITLE
Symbol's function definition is void: -non-nil

### ISSUE THREAD

**Issue by pengpengxp** [jacktasia/dumb-jump#147]
I find it was used in this function:
```
(defun dumb-jump-parse-response-lines (parsed cur-file cur-line-num)
  "Turn PARSED response lines into a list of property lists.  Using CUR-FILE and CUR-LINE-NUM to exclude jump origin."
  (let* ((records (--mapcat (when it
                             (let* ((line-num (string-to-number (nth 1 it)))
                                    (diff (- cur-line-num line-num)))
                               (list `(:path ,(nth 0 it) :line ,line-num :context ,(nth 2 it) :diff ,diff))))
                   parsed))
         (results (-non-nil records)))
    (--filter
     (not (and
           (string= (plist-get it :path) cur-file)
           (= (plist-get it :line) cur-line-num)))
     results)))
```
I have installed all the required packages ：
Requires: emacs-24.3, f-0.17.3, s-1.11.0, dash-2.9.0, popup-0.5.3

But It's always void.

**Comment by jacktasia** [comment]
[-non-nil is a dash.el function](https://github.com/magnars/dash.el#-non-nil-list) so this seems like an issue on your end. Do you have any more details? Maybe try re-installing the packages or restarting emacs?

**Comment by jacktasia** [comment]
Closing for now, but happy to re-open if you have any actionable details in the future.

**Comment by paul-xie-rs** [comment]
Because I had download an old dash.el in my `site-lisp' directory. I just fix it by deleting it. Thank you very much :)

**Comment by pengpengxp** [comment]
Because I had download an old dash.el in my `site-lisp' directory. I just fix it by deleting it. Thank you very much :)
