### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by user471** [jacktasia/dumb-jump#15]
`dumb-jump-go` has an error `Wrong type argument: stringp, nil`
Does it need the latest version of ag?
I use version 0.29.1

**Comment by jacktasia** [comment]
Thanks for reporting this. I've been unable to reproduce this so far. What's under point when you try `dumb-jump-go`? Also, what is the extension of the file you're trying to jump from? If there's anything else you can provide it will help me track down what's happening. For instance, an open source project where you're seeing this error when you try to jump. Thanks!

**Comment by jacktasia** [comment]
> Does it need the latest version of ag?

Sorry, it shouldn't need a specific version. It only needs `--nocolor` and `--nogroup`. I have a feeling it's something related to what's under point, the file, or a dependency issue. The first two was what I was trying to eliminate with my first response above.

Do you always get this error when you try to jump or only under certain cases?

**Comment by user471** [comment]
I replace `'` with `"` here
```
         (regex-args (format "\"%s\"" (s-join "|" filled-regexes))))
```
It starts working. But on Windows paths look like this
```
"c:\\project\\js\\test.js
```
so the parsing result is
![path](https://cloud.githubusercontent.com/assets/5988253/13276692/00508c9c-dad3-11e5-9990-77cb8f592c06.png)
I guess the problem is
```
(s-split ":" it)
```

**Comment by jacktasia** [comment]
Thanks so much for expanding on the issue. I am guessing the Windows part of this is the main issue since I've never tested Dump Jump in windows at all :disappointed:. Tonight I'll try spinning up a Windows VM and try to get things working correctly on Windows.

**Comment by jacktasia** [comment]
Sorry took longer than expected to get Windows all setup. It's working for me in Windows with `ag` now. Please give it another try when you have a moment and let me know how it goes. Thanks!

**Comment by user471** [comment]
It works, thanks.
