### ISSUE TITLE
Julia-lang support

### ISSUE THREAD

**Issue by AShedko** [jacktasia/dumb-jump#159]
Is there a chance support for julia (julialang.org) is coming?

It just reached 46 on TIOBE this august and it has an emacs mode.

**Comment by jacktasia** [comment]
@AShedko Thanks for opening this issue! I've just pushed up _basic_ julia support. I have zero experience with julia, but I was able to successfully jump around[ this julia repo I found](https://github.com/GiovineItalia/Gadfly.jl).

The changes should be available via MELPA in ~6  hours. Please let me know if you run into any issues with it or have any specific requests. Thanks!

**Comment by jacktasia** [comment]
This is now on MELPA. Please let me know if you run into any issues with it or have any specific requests. Thanks!
