### ISSUE TITLE
Support a few more file extensions for PHP

### ISSUE THREAD

**Issue by kostajh** [jacktasia/dumb-jump#16]
Would be great if PHP support would be enabled for the following file extensions used by Drupal:

- .module
- .install
- .test
- .profile
- .theme
- .inc

See https://github.com/arnested/drupal-mode/blob/b4a66092bddc471884b2746d69fd7e8853b4b79f/drupal-mode.el#L916 for reference

**Comment by jacktasia** [comment]
Thanks for bringing this up. I would like to support this but my only concern is mapping seemingly generic extensions directly to PHP. I am leaning towards a solution where if an extension explicitly supported it falls back to using the current major mode somehow. Let me think about this a little bit and I will try to commit something tonight or tomorrow to handle this case. Thanks!

**Comment by jacktasia** [comment]
Hi @kostajh 

I pushed something up that should fix this. I cloned a drupal project and was able to jump from arbitrary file extensions when I was in `drupal-mode` (`php` major-mode). Please give it a try and report back when you get a chance (and re-open if there's an issue). Please note it may take up to 12 hours for this to be available via MELPA.

Thanks again for reporting this and please don't hesitate to bring up new issues or ideas going forward!

**Comment by kostajh** [comment]
Cool, I'll try it out! Thanks.
