### ISSUE TITLE
Support Finding Definitions from HAML

### ISSUE THREAD

**Issue by sshaw** [jacktasia/dumb-jump#161]
Not sure if explicit HAML support is needed or some config setting is required to piggyback on the supported language using HAML.

**Comment by jacktasia** [comment]
Thanks for opening this! I'd definitely like to support something like this. Right now dumb jump figures out what language you're using by the file extension or major mode of the file you're jumping from. If HAML means always jump to ruby within the project then this should be very easy to add. I don't really use ruby or HAML, but it seems like this is the case, yes? If not, I'd need to add in a way to set (probably via `.dumbjump` config file) or detect the repo's/project's language.

**Comment by jacktasia** [comment]
@sshaw Actually [it looks like](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L904) it _should_ already work with files with `.haml` extension. Are you using a different extension? If it's not working for you can you please share the repo or details so I can try to get a fix in? Thanks!

(Also, btw I populated that link above using `git-link` in emacs. Great package!)

**Comment by sshaw** [comment]
> it looks like it should already work with files with .haml extension. Are you using a different extension? 

I was using a 201612 version. Using the latest version it works. 

How about ERB? There I get `Could not find rules for '.erb file'.`. 

One thing to note is that HAML can be used in other languages.

**Comment by jacktasia** [comment]
> I was using a 201612 version. Using the latest version it works.

Gotcha, makes sense. Glad it's working for you now.

> How about ERB? There I get Could not find rules for '.erb file'..

There was no rule for that, but [I just pushed it up](https://github.com/jacktasia/dumb-jump/commit/6cc7a67a796b9a8a216bac83241b214a2ba6769b). It can take a few hours before MELPA picks up the change though.

> One thing to note is that HAML can be used in other languages.

Thanks for the heads up. Is this currently an issue for you?

**Comment by jacktasia** [comment]
Closing this for now, but if someone comes across this wanting HAML support for another language then please comment here and let me know.

**Comment by sshaw** [comment]
>> One thing to note is that HAML can be used in other languages.
> Thanks for the heads up. Is this currently an issue for you?

Not for me. Thanks!
