### ISSUE TITLE
Clojure predicates not recognized correctly

### ISSUE THREAD

**Issue by agzam** [jacktasia/dumb-jump#168]
It seems when you have:

`(defn dev? ...)` and `(defn dev ...)` - which are clearly two different functions, and if the cursor at `dev`, `dumb-jump-go` would prefer to jump to `(defn dev?)` - the wrong one. 

That I guess happens because `dev?` is at the top of the file, and `dev` is declared few lines later. Nevertheless `dumb-jump` should not see `dev` and `dev?` as equal symbols.

**Comment by agzam** [comment]
This probably simply requires setting `dumb-jump-find-rules` correctly, I'm gonna try doing that, although Emacs regexes sometimes intimidate me.

**Comment by jacktasia** [comment]
Thanks for the report! I think there's a few things going on in this case. I think what you said is correct, but I also think that `(bounds-of-thing-at-point 'symbol)` does not consider the `?` to be part of the symbol at point.

I'll try to look into this further later today (or this week).

If you could try setting `(setq dumb-jump-debug t)` and then triggering this case again and then copy/paste what dumb-jump dumps into the  `*Messages*` buffer here that could be helpful. Thanks!

**Comment by agzam** [comment]
So I have a build.boot file with: `defn- dev-env?` `(deftask dev-env)` when I try to use `dumb-jump-go` from `dev-env` symbol it takes me to `dev-env? function`. This is the output of debug:

    -----
    DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
    ----- 

    cmd: 
        git grep --color=never --line-number --untracked -E \\\(def\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(defn-\?\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(defmacro\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(deftype\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(defmulti\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(defmethod\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(definterface\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(defprotocol\\s\+dev-env\(\$\|\[\^\\w-\]\)\|\\\(defrecord\\s\+dev-env\(\$\|\[\^\\w-\]\) -- /Users/ag.ibragimov/DevProjects/finops-admin/\*.clj /Users/ag.ibragimov/DevProjects/finops-admin/\*.cljc /Users/ag.ibragimov/DevProjects/finops-admin/\*.cljs /Users/ag.ibragimov/DevProjects/finops-admin/\*.cljx

    raw results: 

        src/clj/finops_admin/pages.clj:7:(defn- dev-env? []


    -----
    DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
    -----

**Comment by agzam** [comment]
Maybe it's also worth reviewing how `dumb-jump` works with Clojure forms like:

    (require '[app.server :as srv])
    (require '[app.db :as db])

    (srv/run)
    (db/run)

Do you think it would be possible to make it more intelligent? So it would take to `app.server/run` and to `app.db/run`?

**Comment by jacktasia** [comment]
@agzam Thanks for the debug output! I'll definitely fix things so `deftask` and functions with `?` work as expected in clojure. Probably by this weekend at the latest.

> Do you think it would be possible to make it more intelligent? So it would take to app.server/run and to app.db/run?

It's certainly possible.

> Or that's way too much work?

For me, yes. In my opinion this would make dumb-jump no longer "dumb" and require a pretty big re-write for how things are currently done. The idea for dumb-jump is to "just work" most of the time, but not to give any one language too much special treatment. If you need this level of accuracy for clojure I'd recommend using https://github.com/clojure-emacs/cider

**Comment by agzam** [comment]
>  If you need this level of accuracy for clojure I'd recommend using CIDER

well, here's the thing: https://github.com/syl20bnr/spacemacs/pull/9792

I wish there was something lightweight, maybe based on Lumo, that would help navigating Clojure/script projects. Until then dumb-jump is a good alternative

**Comment by jacktasia** [comment]
@agzam The version of dumb jump now available in MELPA should fix the issue you described here with the `?`s, but I think I also need to add support for `deftask`s? Please let me know how this works for you. Thanks!

**Comment by agzam** [comment]
@jacktasia kudos for fixing it so quickly! I will definitely test it out later today. Should I expect these changes to be on MELPA or should I grab the package from GH?

**Comment by jacktasia** [comment]
> @jacktasia kudos for fixing it so quickly! 

No problem!

> I will definitely test it out later today. 

Awesome, thank you!

>  Should I expect these changes to be on MELPA or should I grab the package from GH?

It looks like MELPA already has the changes so you should just have to update via Emacs (and maybe restart)

**Comment by agzam** [comment]
@jacktasia I just have tried, I think it works correctly now! Thank you very much!

**Comment by jacktasia** [comment]
> @jacktasia I just have tried, I think it works correctly now! Thank you very much!

Awesome! Thanks for letting me know!
