### ISSUE TITLE
Excluding path in .dumbjump doesn't seem to work with rg

### ISSUE THREAD

**Issue by Opioid** [jacktasia/dumb-jump#173]
I have added a .dumbjump next to .gitignore at project root. It has the following content:

-/WebVisualization

Yet, my dumbjump (forcing rg) are full of WebVisualization/* results. Am I using it wrong?

EDIT: After using it on different symbols I did not get WebVisualization results any more, but the problem remained for the original search. Is there some kind of cache?

**Comment by jacktasia** [comment]
>  Is there some kind of cache?

Not in dumb-jump. You can try setting `(setq dumb-jump-debug t)` and looking in *Messages* for the output. If you still think there's a bug and you're willing to share the debug output then I'll dig in and see if I can figure out what's going on. Thanks!

**Comment by Opioid** [comment]
This is part of the result:

`Quit
-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----- 

cmd: 
	rg --color never --no-heading --line-number --type js --type html --type css -g ^"^!/WebVisualization^" ^"^(service^|factory^)\^(['\^"]view['\^"]^|\bview\s*[=:]\s*\^([^^\^)]*\^)\s+=^>^|\bview\s*\^([^^\^)]*\^)\s*[{]^|class\s*view\s*[\^(\{]^|class\s*view\s+extends^|\s*\bview\s*=[^^=\n]+^|\bfunction\b[^^\^(]*\^(\s*[^^\^)]*\bview\b\s*,?\s*\^)?^|function\s*view\s*\^(^|\bview\s*:\s*function\s*\^(^|\bview\s*=\s*function\s*\^(^" d:/Workspace/lwvr_poc2

raw results: 

	d:/Workspace/lwvr_poc2\LWVR\LightweightVRPoC2.mweb\src\Cache.js:17:	Cache.Cache.prototype.prepare = function(view) {
d:/Workspace/lwvr_poc2\LWVR\LightweightVRPoC2.mweb\src\LightweightVRPoC2.js:170:			view = new View.Set(sceneGraph, sceneGraphOverrideSet);
d:/Workspace/lwvr_poc2\LWVR\LightweightVRPoC2.mweb\src\LightweightVRPoC2.js:461:					view = tmp;
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:34:            this.view = [];
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:65:        setView: function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:71:                this.view = [];
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:80:                this.view = [view];
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:89:        addView: function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:96:        removeView: function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:108:            this.view = [];
d:/Workspace/lwvr_poc2\WebVisualization\Gestures.mweb\src\BasicGesture.js:274:                this.view = [];
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:437:        getMouseEvents: function (button, view, ignoreFreeMouseMove) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:493:        getMouseEventsByStates: function (states, button, view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:530:        getPrimaryPointerEventsByStates: function (states, view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:583:        getTouchEvents: function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:633:        getTouchEventsByStates: function (states, view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:731:        addGestureRecognizer: function (gr, view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:1021:        _isInView: function (screenEvt, view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\EventsManager.js:2271:        _registerRecordView: function(view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\ScreenEvent.js:41:            this.view = null;
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\ScreenEvent.js:167:            this.view = newView;
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\ScreenEvent.js:252:        isInView: function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\VisuEvents.mweb\src\TouchEvent.js:38:                    this.view = this.event.touches[index].target; // overload event's target with touch target
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\ViewManager.js:110:                var view = this.views[iKey];
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\ViewManager.js:114:                    view = iNode;
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\ViewManager.js:123:                var view = this.views[iKey];
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\ViewManager.js:127:                    view = null;
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\ViewManager.js:136:                var view = this.views[iKey];
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\ViewManager.js:140:                    view = new Node3D();
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\TrackballControls.js:729:                var view = this.manipulatedViewList[i];
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\TrackballControls.js:741:        TrackballControls.prototype.addViewToGestures = function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\TrackballControls.js:750:        TrackballControls.prototype.removeViewFromGestures = function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\TrackballControls.js:759:        TrackballControls.prototype.addViewToManipulation = function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\Visualization.mweb\src\TrackballControls.js:771:        TrackballControls.prototype.removeViewFromManipulation = function (view) {
d:/Workspace/lwvr_poc2\WebVisualization\WebVisuParameters.mweb\src\CSIAppliedGasTokenParameter.js:26:        execute: function(view, viewParam) {
d:/Workspace/lwvr_poc2\WebVisualization\WebVisuParameters.mweb\src\CSISelectionObject.js:61:            var view = viewManager.getView(this.treeKey);
d:/Workspace/lwvr_poc2\WebVisualization\WebVisuParameters.mweb\src\CSIViewTreeTokenParameter.js:68:        execute: function(view, viewParam) {
d:/Workspace/lwvr_poc2\WebVisualization\WebVisuParameters.mweb\src\CSIViewTreeTokenParameter.js:508:        executeEnd: function(view, viewParam, treeUpdateParam) {
d:/Workspace/lwvr_poc2\WebVisualization\WebVisuParameters.mweb\src\CSIViewTreeUpdateParameter.js:32:            var view = viewManager.getView(this.treeKey);
d:/Workspace/lwvr_poc2\WebVisualization\WebVisuParameters.mweb\src\WebVisuUpdateTransaction.js:128:        this.view = iViewManager ? iViewManager.getView(this.treeKeyID) : null;
d:/Workspace/lwvr_poc2\WebVisualization\WebVisuParameters.mweb\src\CSIViewTreeObjectParameter.js:30:        getParentNode: function (view, viewParam, isBody) {
 `
Maybe it is an issue with forward or backward slashes?

**Comment by netromdk** [comment]
@Opioid, try writing simply:
```
-WebVisualization
```

**Comment by jacktasia** [comment]
@Opioid I am going to close this, but if @netromdk's solution still doesn't work for you please let me know. Thanks!
