### ISSUE TITLE
Still doesn't seem to be working correctly with clojure forms

### ISSUE THREAD

**Issue by agzam** [jacktasia/dumb-jump#174]
Sorry for annoying you again, but it seems `dumb-jump-go` still doesn't recognize clojure forms correctly.

For example, if there is a function called `foo*` and then a macro `foo`, and macro consumes the fn, e.g.:

    (defn- foo* [option]
       ,,,)

    (deftask foo []
      (when @server (foo :start)))
      
instead of jumping to `foo`, it would go to `foo*`, I guess there's gotta be some kind of logic that makes difference between `foo`, `foo*`, `foo?`, `foo!`, `foo-bar`, `foo/foo`, etc.

**Comment by jacktasia** [comment]
Thanks for the report! I think this is similar to the `?` issue which was related to the referral word boundary. Also I need to add `deftask` to the clojure but this should be easy for me to change.

**Comment by jacktasia** [comment]
There's an update available via MELPA which should have a fix for this. Please let me know how it goes. Thanks!
