### ISSUE TITLE
php declaration not found

### ISSUE THREAD

**Issue by Glumanda99** [jacktasia/dumb-jump#183]
I tried to play around with `dumb-jump-force-searcher` and even created a `.dumbjump` file in my project root dir, but it will never find any declaration. This package just doesn't do what it is supposed to do. I've no clue what it is doing but I see no search going on here. It just always ends with 

```
'SomeOfMyClass' php declaration not found.
```

Setting `dumb-jump-debug` won't tell me anything.

The project I'm working on is a symfony project with many bundles.

Would be nice if there is a way to see which folders/files it will search through.

**Comment by jacktasia** [comment]
I see you closed this issue already. Did you figure out why things weren't working for you? If so, it'd be great if you comment back on what you did just in case other people run into similar issues going forward. Thanks!

**Comment by Glumanda99** [comment]
@jacktasia Thanks for your fast response! I was in rage mode, sorry and wanted to sleep a night to think about. So I got it working today, after I read about [how to debug dumb-jump](http://p.cweiske.de/506). I didn't know that before and got angry. Maybe there should be instructions about how to debug this package in the readme?

**Comment by jacktasia** [comment]
> @jacktasia Thanks for your fast response! I was in rage mode, sorry and wanted to sleep a night to think about. So I got it working today, after I read about how to debug dumb-jump. I didn't know that before and got angry. Maybe there should be instructions about how to debug this package in the readme?

Thanks for letting me know! I totally agree. I've updated the README: https://github.com/jacktasia/dumb-jump/blob/master/README.md#debugging-a-jump
