### ISSUE TITLE
No rules for Scheme?

### ISSUE THREAD

**Issue by dleslie** [jacktasia/dumb-jump#184]
Although it appears that `dumb-jump` is aware of Scheme comments, it doesn't appear to understand what to do with `scm` files.

**Comment by jacktasia** [comment]
That's correct. If it's not in the language list in the README then it's not supported (yet). PRs are definitely welcome though!

**Comment by dleslie** [comment]
Sure, @jacktasia how do I execute the tests? I've never used cask.

**Comment by jacktasia** [comment]
It's in the README, here's a direct link to the running tests part: https://github.com/jacktasia/dumb-jump#running-tests

The cask README has instructions on how to install: https://github.com/cask/cask#cask

**Comment by jacktasia** [comment]
> Ha, I completely overlooked that when reading the README. (I swear, I did!)

haha, no problem! it's pretty long now. so totally understandable 😄 

> I'll have a PR for you when I get some free time to hack.

Awesome, thanks! Don't hesitate to ask questions if you have any issues.
