### ISSUE TITLE
Erroneously matches sub-words?

### ISSUE THREAD

**Issue by dleslie** [jacktasia/dumb-jump#186]
I noticed this behaviour just after submitting the Scheme support, but it matches the existing behaviour found in the elisp support.

I think it's best described in code:
https://github.com/dleslie/dumb-jump/commit/47bd47654e5049c83a5cc2aa35747e34b81f85c0

Should those new `not` tests pass? They do not at present, and I suspect it's because `\\j` word boundaries aren't working as intended. Unless the intent is to match sub-words. ;)

**Comment by jacktasia** [comment]
Thanks for opening this! This is probably related to this: #181 and #179 That is, it's about what emacs is getting at point. I think. You can verify by turning on the debug flag which is described in the readme. Please let me know what you find. Thanks!

**Comment by dleslie** [comment]
I was under the impression the `not` tests were applied directly to the underlying search provide, be it `rg`, `ag` or other? Anyhow...

For this:
`(defun tester () ...)`

`thing-at-point` will be `tester` for either `sexp` or `symbol`; but I'm looking for the definition of `test`. I can see people wanting this sort of result to show up, however, because they may be trying to recall the full name of a function that they can only recall the prefix for. Hence the bug in the form of a question. 😄

**Comment by jacktasia** [comment]
Ohhh, I see now. Sorry, when I first read this it was on my phone and clearly read it too fast and assumed it was the issue(s) I mentioned. I see what you're saying now and will look closer soon.

**Comment by netromdk** [comment]
This issue can be closed now, right @jacktasia?

**Comment by jacktasia** [comment]
@netromdk Yeah, that's my understanding. I am closing it. @dleslie Please let me know if you're still running into issues.
