### ISSUE TITLE
ES6 arrow functions and methods.

### ISSUE THREAD

**Issue by jordonbiondo** [jacktasia/dumb-jump#19]
Dumb jump currently wont find arrow function definitions or methods in javascript. Ideally it would be able to find `funcName` when defined in a way below;

``` js

let funcName => (foo) => "bar";

const funcName => (foo) => "bar";

const funcName => (foo) => {
  return "bar";
}

const obj = {
  funcName: (foo) => {
    return "bar";
  }
}

const obj = {
  funcName(foo) {
    return "bar";
 }
}
```

**Comment by jacktasia** [comment]
Thanks for reporting this. I totally agree, and I will look into supporting this tonight after work. The first two,  at least, should be easy to support.

**Comment by jacktasia** [comment]
@jordonbiondo 

ES6 functions should now work.  Please re-open this issue if it doesn't work as expected. 

It may take up to 12 hours for this update to be available via MELPA. In MELPA Stable, it will be `0.3.9`.

Thanks again for the feedback and please let me know if you have more.

**Comment by jordonbiondo** [comment]
Appears to work as desired, thanks!
