### ISSUE TITLE
SML support?

### ISSUE THREAD

**Issue by tkadur** [jacktasia/dumb-jump#195]
Thanks for the great plugin! I was wondering if it would be possible to add support for Standard ML - since OCaml is already supported, I hope it's not too much work, but I'm not sure.

**Comment by netromdk** [comment]
They are related but the [syntax varies a lot](http://adam.chlipala.net/mlcomp/) actually. But I guess support for val/let bindings, functions, and data types are what is mostly needed.

**Comment by jacktasia** [comment]
@tkadur Thanks for opening this issue! 

@netromdk Please let me know if I can help with this. Seems like you know (way) more about SML and OCaml than me. Usually, in these cases, I try to just find a good example repo on GitHub to test against but if you're down to add support then awesome. Thanks!

**Comment by netromdk** [comment]
@jacktasia it has been implemented now. :)
