### ISSUE TITLE
[Elisp] declaration not found

### ISSUE THREAD

**Issue by frankie8518** [jacktasia/dumb-jump#202]
```
(defun mark-word-p (&optional numbers)
  (interactive)
  (mark-text-object 'backward-word 'forward-word nil numbers))

(defun kill-word-p(&optional numbers)
  (interactive)
  (kill-text-object 'mark-word-p numbers)
  (funcall 'after-kill-word-action))

```
Cursor is at `'mark-word-p` in the second function.
After `dumb-jump-go`, minibuffer says `declaration not found`
Tested under `emacs -q`

**Comment by jacktasia** [comment]
Thanks for opening this issue. I haven't been able to reproduce it using your example. Can you please give me the [debug output](https://github.com/jacktasia/dumb-jump#debugging-a-jump) and maybe your emacs version and OS? This will help me pinpoint what exactly is happening, so I can fix it. Thanks!

**Comment by frankie8518** [comment]
I am sorry. Don't know why it won't jump at that time, but it works now.
I like dumb-jump, thanks for your works.
