### ISSUE TITLE
Help adding new language: Latex

### ISSUE THREAD

**Issue by alvarogonzalezsotillo** [jacktasia/dumb-jump#204]
I'm trying to add support for Latex files. 
My first try is to find the definition of a new command:
```
(add-to-list
 'dumb-jump-find-rules
 '(:type "command" :supports ("ag" "grep") :language "tex"
         :regex "newcommand\\{\\\\JJJ"
         :tests ("\\newcommand{\\JJJ}")))
(add-to-list
 'dumb-jump-language-file-exts
 '(:language "tex" :ext "tex" :agtype "tex" :rgtype nil))
```

With this code, dump-jump shows all the occurences of the symbol, not only the lines with <code>\newcommand{\acommand}{....}</code>. Is this a problem with the regexp? there is some other variables/functions to change/implement?

**Comment by netromdk** [comment]
Thanks, @alvarogonzalezsotillo! Feel free to open a PR when you have something working.

When testing it will use "test" in place of "JJJ", so try this instead:
```
(add-to-list
 'dumb-jump-find-rules
 '(:type "command" :supports ("ag" "grep") :language "tex"
         :regex "newcommand\\{\\\\JJJ"
         :tests ("\\newcommand{\\test}")))
```

**Comment by netromdk** [comment]
You can also add the latex comment to `dumb-jump-language-comments`.

Shouldn't your rule work for git-grep and rg also, @alvarogonzalezsotillo?

**Comment by alvarogonzalezsotillo** [comment]
> Shouldn't your rule work for git-grep and rg also, @alvarogonzalezsotillo?

I have no idea, I'm just using what I get installed 😅

**Comment by jacktasia** [comment]
@alvarogonzalezsotillo Thanks for working on this!

I am guessing `dumb-jump-fallback-search` is what's happening here. It's on by default and basically if it's on and no results are found it will try again just searching for the term under point. You might want to turn this off with `(setq dumb-jump-fallback-search nil)` and try again.

Try looking at the [debug output](https://github.com/jacktasia/dumb-jump#debugging-a-jump) too.

I hope that helps. Please let me know if it doesn't or you need help with anything else. Thanks!

**Comment by alvarogonzalezsotillo** [comment]
I made some changes to support `newcommand` and `newenvironment`: #205 
Thanks for your tips!
