### ISSUE TITLE
ruby grep rule for "alias" and "alias_method"

### ISSUE THREAD

**Issue by muirrn** [jacktasia/dumb-jump#208]
We use method aliasing occasionally in our ruby code base and I found dumb jump didn't know about them. I'm using this rule, which I think is generalizable for everyone:

```
    (:type "function" :supports ("ag" "rg" "git-grep") :language "ruby"
           :regex "(^|\\W)alias(_method)?\\W+JJJ(\\W|$)"
           :tests ("alias test some_method"
                   "alias_method :test, :some_method"
                   "alias_method ’test’ ’some_method’"
                   "some_class.send(:alias_method, :test, :some_method)")
           :not ("alias some_method test"
                 "alias_method :some_method, :test"
                 "alias test_foo test"))
```

Of course it doesn't take you to the _actual_ definition of the method, but taking you to the alias definition is halfway there and better than nothing.

Finally I want to say dumb jump works great! I tried robe for ruby, and while it is very smart, it is often too smart (e.g. taking you deep inside some generic metaprogramming code where the function was actually defined, but far away from the symbol you are looking for). Dumb jump definitely doesn't have the too-smart problem!

**Comment by jacktasia** [comment]
> We use method aliasing occasionally in our ruby code base and I found dumb jump didn't know about them. I'm using this rule, which I think is generalizable for everyone:

Awesome! Thanks for sharing this! I made a PR adding them here #209.

> Finally I want to say dumb jump works great! I tried robe for ruby, and while it is very smart, it is often too smart (e.g. taking you deep inside some generic metaprogramming code where the function was actually defined, but far away from the symbol you are looking for). Dumb jump definitely doesn't have the too-smart problem!

I am happy to hear dumb jump is a good solution for you. People don't always (immediately) see the value in the "dumb" strategy. I really appreciate the kind words :slightly_smiling_face:
