### ISSUE TITLE
ivy selector doesn't support ivy-call

### ISSUE THREAD

**Issue by amosbird** [jacktasia/dumb-jump#211]
Executing `ivy-call` on candidate has no effect at all.

**Comment by jacktasia** [comment]
Thanks for opening this.

> Executing ivy-call on candidate has no effect at all.

Can you please expand on what you're expecting this to do? I assume keep the candidate list up but still jump to it? Thanks!

**Comment by amosbird** [comment]
yup, like previewing the candidate. `counsel-rg` supports that.

**Comment by jacktasia** [comment]
I think #236 will address this.
