### ISSUE TITLE
dumb-jump-quick-look Does not jump on a single result

### ISSUE THREAD

**Issue by olymk2** [jacktasia/dumb-jump#214]
If I hover over some code and call dumb-jump-quick-look it displays a single result if you hit enter it does not jump, how ever if multiple results are returned I can move up and down the list and hit return to jump.

Seems I should get the same action for a single result

**Comment by jacktasia** [comment]
Thanks for opening this! `dumb-jump-quick-look` is meant purely to see a "quick look" and not actually jump. The docs are unclear on this and I have updated them now. #215 

Thanks

**Comment by olymk2** [comment]
Okay this feels like It would be quite nice to have, ass you can use it in place of plain old jump and get a bit of info before you jump.

but thanks for clarifying :)
