### ISSUE TITLE
ES6 classes

### ISSUE THREAD

**Issue by jordonbiondo** [jacktasia/dumb-jump#22]
Given the following scenario:
```js
const instance = new MyCla|ss(3, 4);
```

Dumb jump will find the definition of `MyClass` if it defined as follows:

```js
function MyClass(a, b) {
    this.a = a;
    this.b = b;
}
```

But it will not find the definition of `MyClass` if it defined using ES6 classes.	

```js
class MyClass {

    constructor(a, b) {
        this.a = a;
        this.b = b;
    }
}
```

I don't think jumping to the `constructor` would be necessary but it would be nice. IMO, jumping to `class MyClass {` would suffice.

**Comment by jacktasia** [comment]
Thanks for the report! This should be really easy for me to add. I'll take a stab at it tonight after work.
