### ISSUE TITLE
Please support R

### ISSUE THREAD

**Issue by adouzzy** [jacktasia/dumb-jump#24]

**Comment by jacktasia** [comment]
Hi @adouzzy 

Thanks for the suggestion! I want to support as many languages as possible. I don't know R at all, but it looks it would be pretty easy to provide basic support. If you have a good R repo to test against, please let me know. If not, I think I'll be looking off of this one: https://github.com/twitter/AnomalyDetection

Thanks again!

**Comment by jacktasia** [comment]
Hi @adouzzy

I've added basic R support. It seems to work correctly moving around the [AnomalyDetection](https://github.com/twitter/AnomalyDetection) repo.

Please open a new issue if you run into any problems. This release should be available in MELPA within 12 hours.

Thanks again for the suggestion!
