### ISSUE TITLE
support in tramp mode

### ISSUE THREAD

**Issue by kubaroth** [jacktasia/dumb-jump#242]
More of a question then an issue. Has anyone tried using dumbjump with a tramp mode? It is locking up the session for a while and does not jump anywhere. My guess it times out while waiting for a connection.

**Comment by jacktasia** [comment]
I haven't tried for a while, but my understanding is dumb-jump works with tramp mode if you have the correct searcher installed on the remote host. See: #191  https://github.com/jacktasia/dumb-jump/issues/137

**Comment by kubaroth** [comment]
ok thanks for a quick answer. I will take a another look.
