### ISSUE TITLE
Jumping to namespaced classes doesn't work in Ruby

### ISSUE THREAD

**Issue by patbl** [jacktasia/dumb-jump#243]
In Ruby, the conventional way to namespace a class is to nest it in one or more modules:

```ruby
module Health
  module Checks
    class QueueGrowth
      [code for checking queue growth]
    end
  end
end
```

(For the record, there's a less conventional, worse way of writing this code that I don't think Dumb Jump needs to support:

```ruby
class Health::Checks::QueueGrowth
end
```
)

You can then reference the class like this:

* anywhere: `::Health::Checks::QueueGrowth`
* anywhere without a conflicting namespace: `Health::Checks::QueueGrowth`
* inside the `Health` module: `Checks::QueueGrowth`
* inside the `Health::Checks` module: `QueueGrowth`

`dumb-jump-go` usually doesn't know what to do when you call it with any of those references I just listed. It either jumps to the very thing your cursor is over (if it's the only reference of its type), or it presents a list of other references to the class, but not the class itself:

![image](https://user-images.githubusercontent.com/1735266/49192910-fbe78000-f331-11e8-9fb5-8bff000ec65a.png)

It would be a bit of work to make Dumb Jump know about the intricacies of Ruby namespacing, but I think things would be greatly improved simply by looking only for the bit after all the colons (`QueueGrowth` in the example above), and presenting a list of all the places that `module QueueGrowth` or `class QueueGrowth` appear in the code.

The code base I work in uses namespaces extensively, and I usually end up copying the bit after the colons, calling `dumb-jump-go-prompt`, and pasting.

**Comment by jacktasia** [comment]
Thanks for the report! I think this should be pretty easy to support. I'll push up something soon.
