### ISSUE TITLE
dumb-jump and fortran

### ISSUE THREAD

**Issue by ssnnoo** [jacktasia/dumb-jump#245]
dumb-jump currently does not work well with fortran files in upper-case, e.g. SUBROUTINE instead of subroutine (always shows all occurrences of the symbole for manual selection). 
e.g. (setq dumb-jump-rg-cmd '"rg -i") is a workaround (case insensitive search) but would be nice to include this in a proper way

also  for historic reasons file-endings are often uppercase -> .F90 insetad of .f90, so would be nice to include these, e.g.

(:language "fortran" :ext "F90" :agtype "fortran" :rgtype "fortran")
(:language "fortran" :ext "F95" :agtype "fortran" :rgtype "fortran")

Keep up the great work!

**Comment by jacktasia** [comment]
Thanks for the report! I'll try to make a PR soon that implements these ideas.

**Comment by jacktasia** [comment]
@ssnnoo Thanks again for opening this issue. I made some Fortran changes please give them a try when you have a moment. They should land in MELPA in ~6 hours.

**Comment by jacktasia** [comment]
@ssnnoo Awesome, thanks for letting me know
