### ISSUE TITLE
quick-look multiple results

### ISSUE THREAD

**Issue by sebastianpech** [jacktasia/dumb-jump#249]
Hi,I don't really understand the behavior of `dumb-jump-quick-look` when multiple matches are found. Currently it shows the results in ivy or helm and then jumps to the selection. 
What's the reasoning for not just showing a multiline tooltip?
Especially for languages supporting multiple dispatch this would be really handy as it quickly shows all possible arguments to the function under the cursor.

**Comment by jacktasia** [comment]
Sorry for the delay in responding. This issue somehow fell through the cracks. 

> I don't really understand the behavior of `dumb-jump-quick-look` when multiple matches are found. Currently it shows the results in ivy or helm and then jumps to the selection.
What's the reasoning for not just showing a multiline tooltip?

I honestly don't have a good reason for this. I personally never really used the quick-look feature after I first added it. It's possible this is a bug, and we shouldn't use ivy/helm in this context. Maybe this should be a setting to always force the tooltip?

**Comment by sebastianpech** [comment]
It's working, very nice. Thanks

**Comment by jacktasia** [comment]
Great, thanks for confirming!
