### ISSUE TITLE
Question: Multi-line patterns with git-grep+ag?

### ISSUE THREAD

**Issue by mhcerri** [jacktasia/dumb-jump#250]
Hi,

Do you think it would possible to implement a way to first search simply by the symbol name using `git grep` and then use the set of files returned to do an `ag` search with the full pattern?

**Comment by jacktasia** [comment]
Hi @mhcerri 

That's certainly possible, but I don't think it would be a trivial change. Can you provide some details on why you want/need that functionality?

**Comment by mhcerri** [comment]
I would love to use it on the linux kernel source tree. Multi-line declarations are very common there and anything besides `git grep` is very slow.

I can try to put together a pull request for that. Do you have any suggestions or directions on how to proceed?

**Comment by jacktasia** [comment]
> Multi-line declarations are very common there and anything besides git grep is very slow.

Gotcha, thanks for the context.

> Do you have any suggestions or directions on how to proceed?

I think so. Let me think about this for a bit and get back to you. It's possible there's a couple of places to hook into that would make this really easy.

**Comment by jacktasia** [comment]
@mhcerri I apologize for the delay on getting back to you on this. I think I have come up with a pretty good way to hook in the functionality you have suggested. That said, I would like to test it against something real before I concert my bash test into Emacs Lisp. Can you please recommend a good function with a multi-line declaration in the kernel to test against? By "good" I mean whatever criteria that makes sense to you but one that you would think would be particularly slow for whatever reason would probably be best. Thanks!

**Comment by jacktasia** [comment]
Thanks for the info! I am going to try to implement and PR this soon.

**Comment by jacktasia** [comment]
@mhcerri I got something seemingly working well in #254  Can you please try it for your needs and give me any feedback you may have there? Thanks!

**Comment by mhcerri** [comment]
Hi, @jacktasia.

I tested several symbols and it works perfectly so far. It was able to find multi-line signatures way faster. I also tested it on smaller repos and it works flawless as well, returning immediately.

Thank you a lot!

**Comment by jacktasia** [comment]
@mhcerri Awesome! Thanks for trying it out. I am going to keep the PR open until I can add some more tests then I'll merge. Please let me know if you run into anything. Thanks!
