### ISSUE TITLE
Common Lisp

### ISSUE THREAD

**Issue by teymuri** [jacktasia/dumb-jump#251]
Are there any support for Common Lisp or planned to be? By doing `C-A-g` in emacs lisp or common lisp i get after some time:

> Took over 2s to find ’foo’. Please install ag or rg, or add a .dumbjump file to ’/home/amir’ with path exclusions

I am using Emacs 25.1.1 on Debian

**Comment by jacktasia** [comment]
> Are there any support for Common Lisp or planned to be?

Emacs Lisp should work, but Common Lisp isn't currently supported. That said, I am guessing we could get pretty good support by just borrowing from the emacs lisp rules. Is there a public Common Lisp project that you think would be a good general example? If so, I can add Common Lisp rules by testing against it.  

> By doing C-A-g in emacs lisp or common lisp i get after some time:

It looks like your using dumb-jump in a directory without a project denoter. My comments here will probably help: https://github.com/jacktasia/dumb-jump/issues/130#issuecomment-298692151 #126 please let me know if you continue to have issues.

**Comment by teymuri** [comment]
I still don't understand what should i do for dumbjump to find the functions (say in elisp). Putting a .dubjump in the home and telling him where not to look for the function under the point should solve it?

**Comment by jacktasia** [comment]
dumb-jump looks for projects/repos. The reason you're having issues is because you appear to not be in one so it's searching ALL of your home directory which probably has a lot of nested subdirectories.

You need to have a directory that is not your actual home directory and add a `.dumbjump` file and your elisp code and then it should work. If you use something like git this "just works" because a `.git` directory is also a project denoter.

If this doesn't help please provide more details. I am making a few assumptions here.

**Comment by jacktasia** [comment]
@teymuri I added very basic support for Common Lisp. This should now be available via MELPA if you want to give it a try. For now, there's only support for `defun` and `defparameter`, but please let me know if you think it should support anything else. Thanks!

**Comment by teymuri** [comment]
Thank you for your help!  In Elisp doing `C-M-g` jumps to the definition, but doing this in Lisp a drop down list is showed with many possible directories and files having a funtion-variable of the same name too choose from. Is this part of the concept of dumbjump or is it only a thing with Common Lisp?

**Comment by jacktasia** [comment]
> but doing this in Lisp a drop down list is showed with many possible directories and files having a funtion-variable of the same name too choose from. Is this part of the concept of dumbjump or is it only a thing with Common Lisp?

This sounds like the same project denoter issue as earlier, but I can't say for sure without more info on your directory/repo structure.
