### ISSUE TITLE
Ripgrep supports multi-line patterns -> update Readme.md

### ISSUE THREAD

**Issue by thisch** [jacktasia/dumb-jump#255]
The readme file recommends to use "ag" as the searcher if the support for multline signatures is needed. 

Since rg [now](https://www.reddit.com/r/rust/comments/9dxewq/ripgrep_0100_released_pcre2_and_multiline_support/) supports multiline pattterns this recommendation should be removed/updated.

**Comment by jacktasia** [comment]
Thanks!

**Comment by thisch** [comment]
Thx for this quick update. I'm not sure but I think that we also have to adapt the source code of dumb-jump, since multiline support in ripgrep is enabled with the -U cmd line flag.

**Comment by jacktasia** [comment]
> I'm not sure but I think that we also have to adapt the source code of dumb-jump, since multiline support in ripgrep is enabled with the -U cmd line flag.

I think you're right. I am opening this until I get a chance to make and test this change. This should also allow us to support more rules.
