### ISSUE TITLE
Trouble with Emacs 24.3 on Ubuntu 14.04

### ISSUE THREAD

**Issue by caldwell** [jacktasia/dumb-jump#26]
I installed from MEPLA (version `20160427`) and get this error when I try to `dumb-jump-go` in some Go source code:

    dumb-jump-fetch-results: Wrong number of arguments: #[(thing) "^HÂN\203^K^@^HÂN \207Ã^H!\211^Y\205^X^@  @       A{)\207" [thing bounds thing-at-point bounds-of-thing-at-point] 3 ("/usr/share/emacs/24.3/lisp/thingatpt.elc" . 2294)], 2

I'm using the `emacs24-nox` package, version `24.3+1-2ubuntu1` and `M-x version` says `GNU Emacs 24.3.1 (x86_64-pc-linux-gnu) of 2014-03-07 on lamiak, modified by Debian`.

**Comment by tylerhsu** [comment]
I have the same issue, same emacs version, same ubuntu version.

**Comment by jacktasia** [comment]
Thanks for reporting this. I only run tests for `24.4` and `24.5` so I am guessing this is related to the old version you're using. I'll update the package to reflect the supported versions.

**Comment by caldwell** [comment]
I was able to hack it into working by removing the 3rd argument (`'t`) to the 2 `thing-at-point` calls in `dumb-jump-fetch-results`.

**Comment by jacktasia** [comment]
@caldwell Thanks for looking into this. I should be able to use this info to pretty easily support `24.3` too. I will look into it this weekend. Thanks again.

**Comment by jacktasia** [comment]
24.3 should work now with #52. It will take a few hours to be available via MELPA. 

@caldwell Thanks again for bringing this up and all your work on emacsformacosx.com!
