### ISSUE TITLE
Feature: Integration with xref

### ISSUE THREAD

**Issue by joca-bt** [jacktasia/dumb-jump#262]
Has an integration with `xref` been considered?

**Comment by jacktasia** [comment]
Thanks for opening this! Other than  https://github.com/jacktasia/dumb-jump/pull/74 it's unclear to me what other kinds of integration there should be. To be honest, in the very little amount of time I've spent looking at `xref` its interface never made much sense to me.

What functionalty are you looking for exactly?

**Comment by joca-bt** [comment]
Didn't know about #74. The `xref` interface is still experimental and lacks proper documentation.

Just re-using `xref` for going to definition and back. Using its UI and keybindings.

**Comment by jacktasia** [comment]
> The `xref` interface is still experimental and lacks proper documentation.

Ok, thanks for the info. That's kind of a deal breaker for me doing it myself. If someone wanted to PR optional support for it then it would certainly be welcome.

> Using its UI and keybindings.

My understanding is most people like `helm` or `ivy`, but again if someone wanted to add support for an `xref` option for the `defcustom dumb-jump-selector` then it would be welcome.

For keybindings, I am unlikely to add in more built-in ones since `use-package` makes it so easy for anyone to use whatever keybindings they want, but I'd be open to PRs if it's done in a clean way.

**Comment by jacktasia** [comment]
Ah, I guess you mean by making `dumb-jump` an `xref` backend then you would get everything you're describing. Regardless I am open to PRs for it, but I personally won't add it.

**Comment by joca-bt** [comment]
I've been looking into this and in fact it doesn't make much sense since `xref` API has:
- `xref-backend-apropos',
- `xref-backend-definitions',
- `xref-backend-identifier-at-point',
- `xref-backend-identifier-completion-table',
- `xref-backend-references'
and `dumb-jump` focus only on xref-backend-identifier-at-point.

I've integrated `dumb-jump` with `xref-backend-identifier-at-point` but I am unsure whether it will be helpful for other people since if they use `xref` extensively it won't help them much.

**Comment by jacktasia** [comment]
Thanks for looking into this. I am also unsure, but i am happy to take a look at what you have to see if you want to PR it or share a link to your branch.

**Comment by joca-bt** [comment]
I'm currently tackling an improvement. I'm using `dumb-jump-get-results` go get the results but when comparing with what is actually shown when using `dumb-jump-go` there are some differences. Is `dumb-jump-go` making some filtering? Maybe in `dumb-jump-handle-results`? Also what does `:diff` store?

**Comment by joca-bt** [comment]
I guess `dumb-jump-handle-results` looks at the context type and shows only the relevant entries per that. While `dumb-jump-get-results` returns all text matches. Is this the case?

**Comment by jacktasia** [comment]
> Would you think it would be easy to split searching, from filtering, and from visiting the file into different functions so that each one can be used individually?

I would think so, but I can take a closer look after work tonight. This probably makes sense to do regardless of `xref`.

**Comment by jacktasia** [comment]
So I looked into this and it's a little more complex than I thought/was hoping to split this out, but I am still actively looking into and will continue with it again tonight.

**Comment by joca-bt** [comment]
Thanks! I might have some free time in the weekend to look into it as well.

**Comment by joca-bt** [comment]
I was able to extract the filtering to another function and clean-up the code, which was a bit confusing, but still need to integrate it with `dumb-jump-handle-results`. Should create a PR soon.

**Comment by joca-bt** [comment]
See #277.

**Comment by joca-bt** [comment]
Closing this ticket. I had my local hack in order for it to work but I'm no longer using it since I moved on to LSP. Won't find the motivation to finish this.

**Comment by phikal** [comment]
In case there's any interest in this issue, based on my proposed rewrite (#334) it was rather easy to implement a working xref backend: https://github.com/phikal/dumb-jump/commit/ab26b48f36c1a91a4ede8413258d137bce40e383
