### ISSUE TITLE
Include Python path modules in search

### ISSUE THREAD

**Issue by jcaw** [jacktasia/dumb-jump#263]
Dumb jump is great as a fallback for Python, but it only searches the project - it won't search modules on the Python path. For example:

```python
import threading

threading.Thread()
```

Let's say I want to jump to `Thread`, to see how it works. `dumb-jump` won't let me - it will only search the current project. 

It seems like this could be fixed with a `.dumbjump` file, but that's clunky. It might be smoother to extract the python path automatically before jumping. 

Let's assume we could extract the directories on python's path. Is there a way to automatically provide a list of extra directories to `dumb-jump` in a particular mode? If so I'd be happy to try implementing this.

**Comment by jcaw** [comment]
I did some experiments and came up with a very hacky bit of code to test the concept, but the amount of new files slows down the search quite a bit.

I think the only way to make this smooth would be to search the project's path (and `.dumbjump` paths) and present the results, then search the python path in the background, updating the results asynchronously. I'm thinking that's probably out of `dumb-jump`'s scope. 

```emacs-lisp
(defun shell-command-to-string-if-successful (command)
  "Get stdout from a shell command as a string, iff successful.

If the command exits with code 0, it returns stdout. If not, it
returns nil."
  (let ((output-code)
        (stdout-string))
    (with-temp-buffer
      (setq output-code (shell-command command (current-buffer)))
      (setq stdout-string (buffer-string)))
    (if (= output-code 0)
        stdout-string
      nil)))

(defun my-dumb-jump--python-get-paths ()
  "Get a list of python search paths for the current directory.

Specifically, this function runs a python process in the current
directory, and returns the contents of `sys.path'.

It will fail gracefully if the python path can't be found, and
just return nil."
  (let ((raw-python-paths (shell-command-to-string-if-successful
                           "echo \"import sys;print(sys.path)\" | python")))
    (when raw-python-paths
      ;; Remove Python formatting
      (--mapcat
       (setq raw-python-paths (replace-regexp-in-string it "" raw-python-paths))
       ;; Patterns to remove
       '(;; Newlines
         "\n"
         ;; List start
         "^\\[['\"]"
         ;; List end
         "['\"]\\]$"))
      ;; Prep the string for splitting - replace separators
      (setq raw-python-paths (replace-regexp-in-string "['\"], ['\"]" "\n" raw-python-paths))
      (split-string raw-python-paths "\n" t nil))))

(defun dumb-jump-fetch-results (cur-file proj-root lang config &optional prompt)
  "Hacked version of `dumb-jump-fetch-results` that adds the
python path when lang is \"python\", and determines the search
program individually for each directory (to avoid using git grep
on external directories)."
  (let* ((cur-line (if prompt 0 (dumb-jump-get-point-line)))
         (look-for-start (when (not prompt)
                           (- (car (bounds-of-thing-at-point 'symbol))
                            (point-at-bol))))
         (cur-line-num (line-number-at-pos))
         (proj-config (dumb-jump-get-config proj-root))
         (config (when (s-ends-with? ".dumbjump" proj-config)
                   (dumb-jump-read-config proj-root proj-config)))
         (found-symbol (or prompt (dumb-jump-get-point-symbol)))
         (look-for (or prompt (dumb-jump-process-symbol-by-lang lang found-symbol)))
         (pt-ctx (if (and (not prompt) (not (string= cur-line look-for)))
                     (dumb-jump-get-point-context cur-line look-for look-for-start)
                   nil))
         (ctx-type
          (dumb-jump-get-ctx-type-by-language lang pt-ctx))

         (exclude-paths (when config (plist-get config :exclude)))
         (include-paths (when config (plist-get config :include)))
         ; we will search proj root and all include paths
         (search-paths (-distinct (-concat (list proj-root)
                                           include-paths
                                           (when (string= lang "python")
                                             (my-dumb-jump--python-get-paths)))))
         ; run command for all
         (raw-results (--mapcat
                       ;; Work out the search command to use separately for each directory.
                       (let* ((gen-funcs (dumb-jump-pick-grep-variant it))
                              (parse-fn (plist-get gen-funcs :parse))
                              (generate-fn (plist-get gen-funcs :generate))
                              (searcher (plist-get gen-funcs :searcher))
                              (regexes (dumb-jump-get-contextual-regexes lang ctx-type searcher)))
                         (dumb-jump-run-command look-for it regexes lang exclude-paths cur-file
                                                cur-line-num parse-fn generate-fn))
                       search-paths))

         (results (--map (plist-put it :target look-for) raw-results)))
    `(:results ,results :lang ,(if (null lang) "" lang) :symbol ,look-for :ctx-type ,(if (null ctx-type) "" ctx-type) :file ,cur-file :root ,proj-root)))
```

**Comment by jacktasia** [comment]
> I think the only way to make this smooth would be to search the project's path (and .dumbjump paths) and present the results, then search the python path in the background, updating the results asynchronously. 

Yeah, to make this always fast that's probably true.

> I'm thinking that's probably out of dumb-jump's scope.

Yes, I definitely agree. That said, doing something like this in the root of a project works well enough for me, but this will be a function of a lot of things including installed packages:

`python -c 'import sys; open(".dumbjump", "w").write("\n".join(["+" + x for x in sys.path if x and not x.endswith(".zip") and not x.endswith(".egg")]))'
`
or only site-packages:

`python -c 'import sys; open(".dumbjump", "w").write("\n".join(["+" + x for x in sys.path if x and "site-packages" in x]))'`

If you haven't looked you might want to check out https://github.com/jojojames/smart-jump, which has smarter language specific jumping and then will fallback to dumb-jump.

**Comment by jcaw** [comment]
>`python -c 'import sys; open(".dumbjump", "w").write("\n".join(["+" + x for x in sys.path if x and not x.endswith(".zip") and not x.endswith(".egg")]))'`

This is nice, thankyou. Good idea, I'll try wrapping it up and putting it in my config.

>If you haven't looked you might want to check out https://github.com/jojojames/smart-jump, which has smarter language specific jumping and then will fallback to dumb-jump.

I like it. I'm using Spacemacs at the moment, which has similar functionality. Tries the contextual jumpers first, then falls back to dumb jump. But the contextual jumpers can be unreliable, especially on Windows, which makes navigating `site-packages` a pain without booting up PyCharm.
