### ISSUE TITLE
Dart?

### ISSUE THREAD

**Issue by bbuccianti** [jacktasia/dumb-jump#264]
There is too dificult to add support for Dart language?

**Comment by jacktasia** [comment]
Thanks for opening this.

>  too difficult to add support for Dart language?

It should be easy enough. This is just the first request for it. I'll try to look into adding Dart soon.

**Comment by bbuccianti** [comment]
It would be great to jump to the language source when you want. It have great comments!

**Comment by bbuccianti** [comment]
Can I help you in any way?

**Comment by jacktasia** [comment]
> Can I help you in any way?

Sure, I merged a PR to add very basic Dart support that worked fine for me. If you can test it now or when it reaches MELPA in a few hours then that would be great. Thanks!

**Comment by bbuccianti** [comment]
Seems like it's function very well!! Thank you!

There is a way to enable the jump to the Dart code as well? 

Suppose that I'm using a function Blabla() that is implemented in Dart source code. Ideally I can dumb-jump-go on Blabla() and it takes me to the Dart source code definition.

Again, thanks for this great package.

**Comment by jacktasia** [comment]
> Seems like it's function very well!! Thank you!

Great, thanks for letting me know!

> There is a way to enable the jump to the Dart code as well?

If you're using `ag` or `rg` you can add a `.dumbjump` file to your project root can add other paths to include/exclude in the search. 

For example, to add dart's code you would do something like this:

update your emacs confg:

```elisp
(setq dumb-jump-force-searcher 'ag) 
```

and then run something like the following:

```bash
echo '+~/code/dart-sdk/' >> ~/code/your-dart-project/.dumbjump 
git clone https://github.com/dart-lang/sdk dart-lang-sdk ~/dart-lang-sdk
```


[more details](https://github.com/jacktasia/dumb-jump#example-dumbjump)
