### ISSUE TITLE
Request: add an option for enabling --recurse-submodules with git-grep

### ISSUE THREAD

**Issue by DeeeeLAN** [jacktasia/dumb-jump#267]
Hi, my projects all make heavy use of submodules, but git-grep by default does not search them. Adding a flag would be great, because I do not have the ability to install the other search options.

**Comment by jacktasia** [comment]
I merged a change for this. This should be available via MELPA in the next few hours and then you can just add this to your config:

`(setq dumb-jump-git-grep-search-untracked-args " --untracked --recurse-submodules")`

**Comment by DeeeeLAN** [comment]
Thanks. Is the untracked option required for this to work? And does this allow for any git grep flags?

**Comment by jacktasia** [comment]
So `dumb-jump-git-grep-search-untracked` has to be `t`, but then you can do whatever you want inside of `dumb-jump-git-grep-search-untracked-args` so you can actually drop `--untracked` and/or add more arguments. Just make sure it starts with a space.

**Comment by DeeeeLAN** [comment]
Awesome, thanks.
