### ISSUE TITLE
Support for Groovy

### ISSUE THREAD

**Issue by hajovonta** [jacktasia/dumb-jump#274]
Hi,
great package! Are there plans to support for Groovy files? I have plenty of them!
Thanks,
hajo

**Comment by jacktasia** [comment]
Howdy, thanks for opening this. So dumb-jump should have basic support for groovy. What file extension are you using? What happens when you try to jump in a groovy file?

**Comment by jacktasia** [comment]
I am going to close this, but please let me know if you have feedback for the groovy support.
