### ISSUE TITLE
Broken for Javascript/React using ripgrep backend

### ISSUE THREAD

**Issue by fnzen** [jacktasia/dumb-jump#276]
I'm using dumb-jump since more than a year for Javascript/React. Since some days (unfortunately I don't know the exact point in time) it stopped working.

For example on this file/line: https://github.com/spences10/react-tic-tac-toe/blob/master/src/components/App.js#L135

Jumping to the `jumpTo` class method is not working any more, the error message given in Emacs is:

```
’jumpTo’ javascript function declaration not found.
```

My configuration for dumb-jump is:
```
(setq dumb-jump-force-searcher 'rg)
(setq dumb-jump-selector 'ivy)
```

**Comment by jacktasia** [comment]
Thanks for the report! Can you please tell me your version of `rg` (`rg --version`)?

**Comment by fnzen** [comment]
ripgrep 0.9.0
-SIMD -AVX

I'm on Fedora 29.

**Comment by jacktasia** [comment]
Thanks for the info. Can you update to ripgrep 0.10 and also update dumb-jump if you haven't recently? Relatively recently I made a change to enforce that as a min version because they made a bunch of changes (particularly around multi-line matching)

**Comment by fnzen** [comment]
I compiled ripgrep from source:

ripgrep 0.10.0 (rev 0913972104)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

Unfortunately I still get the same error message. When I comment the line containing `dumb-jump-force-searcher` then dumb-jump works.

**Comment by jacktasia** [comment]
Thanks for the update. I cloned the https://github.com/spences10/react-tic-tac-toe repo and tried to jump to `jumpTo` and it worked as expected for me with the most recent dumb-jump and `rg` (Emacs 26.1 on Ubuntu 18.04)

Can you please try turning on debugging as described [here](https://github.com/jacktasia/dumb-jump/blob/59f91b408f6228be035ece10a79b5d460430116a/README.md#debugging-a-jump) and sharing your output?

**Comment by fnzen** [comment]
The problem was the missing PCRE2 support in my ripgrep 0.10.0 build.
I compiled it with `cargo build --release --features 'pcre2'` and then jumping worked.
Thanks for your support and for writing dumb-jump, it works really well even with complicated javascript code.

For completeness, here is the debug output for the two ripgrep versions:

```
ripgrep 0.9.0:

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----- 

cmd: 
	rg --color never --no-heading --line-number -U --pcre2 --type js --type html --type css \(service\|factory\)\\\(\[\'\"\]jumpTo\[\'\"\]\|\\bjumpTo\\s\*\[\=\:\]\\s\*\\\(\[\^\\\)\]\*\\\)\\s\+\=\>\|\\bjumpTo\\s\*\\\(\[\^\(\)\]\*\\\)\\s\*\[\{\]\|class\\s\*jumpTo\\s\*\[\\\(\\\{\]\|class\\s\*jumpTo\\s\+extends\|function\\s\*jumpTo\\s\*\\\(\|\\bjumpTo\\s\*\:\\s\*function\\s\*\\\(\|\\bjumpTo\\s\*\=\\s\*function\\s\*\\\( /home/flo/src-web/react-tic-tac-toe

raw results: 

	error: Found argument '-U' which wasn't expected, or isn't valid in this context

USAGE:
    
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f PATTERNFILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN

For more information try --help
 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----

ripgrep 0.10.0:

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ START
----- 

cmd: 
	rg --color never --no-heading --line-number -U --pcre2 --type js --type html --type css \(service\|factory\)\\\(\[\'\"\]jumpTo\[\'\"\]\|\\bjumpTo\\s\*\[\=\:\]\\s\*\\\(\[\^\\\)\]\*\\\)\\s\+\=\>\|\\bjumpTo\\s\*\\\(\[\^\(\)\]\*\\\)\\s\*\[\{\]\|class\\s\*jumpTo\\s\*\[\\\(\\\{\]\|class\\s\*jumpTo\\s\+extends\|function\\s\*jumpTo\\s\*\\\(\|\\bjumpTo\\s\*\:\\s\*function\\s\*\\\(\|\\bjumpTo\\s\*\=\\s\*function\\s\*\\\( /home/flo/src-web/react-tic-tac-toe

raw results: 

	PCRE2 is not available in this build of ripgrep
 

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----
```

**Comment by jacktasia** [comment]
> The problem was the missing PCRE2 support in my ripgrep 0.10.0 build.
I compiled it with cargo build --release --features 'pcre2' and then jumping worked.

Thanks for the update and providing the debug information! I am glad you got it working again.I will look into updating dumb-jump to surface exact searcher errors instead of swallowing them as a "no results" message.

> Thanks for your support and for writing dumb-jump, it works really well even with complicated javascript code.

I am always happy to help. Thanks for the kind words.
