### ISSUE TITLE
Support for CoffeeScript would be nice

### ISSUE THREAD

**Issue by mck-** [jacktasia/dumb-jump#28]

**Comment by jonboiser** [comment]
Is there a general strategy for adding a new language? I was reading through the code and it looks like you just add a handful of plists for different symbol types in `dumb-jump-find-rules`, then some other variables in the other `defcustoms`.

Do you think you could give a brief checklist of what needs to be done? I can give it a try with coffeescript and write it up as a guide for contributors.

**Comment by jacktasia** [comment]
@jonboiser 

Yes, multiple languages have been added via PR. Some good examples are [lua](https://github.com/jacktasia/dumb-jump/pull/33) and [rust](https://github.com/jacktasia/dumb-jump/pull/57) I've been meaning to [add this to the README](https://github.com/jacktasia/dumb-jump/commit/513a432569a26e10a954ca274b2aa0baeaaed656). Thanks for reminding me. Please let me know if I can help with adding coffeescript.
