### ISSUE TITLE
dumb-jump objc: support objc types in addition to methods and variables

### ISSUE THREAD

**Issue by iamdavidhart** [jacktasia/dumb-jump#281]
Additional ObjC types such as:

@interface & and category declarations
@protocol declarations
@implementation definitions
enum / NS_ENUM / NS_OPTIONS

examples:

From UIKit/UIView.h:

* Interface declaration (including protocol adherence):
NS_CLASS_AVAILABLE_IOS(2_0) @interface UIView : UIResponder <NSCoding, UIAppearance, UIAppearanceContainer, UIDynamicItem, UITraitEnvironment, UICoordinateSpace, UIFocusItem, UIFocusItemContainer, CALayerDelegate>

* Category declarations:
@interface UIView (UIViewGeometry)

* Protocol declarations:
@protocol UICoordinateSpace <NSObject>

* Implementation definitions
@implementation SomeClass
@implementation SomeClass (SomeCategory)

* NS_ENUM:
typedef NS_ENUM(NSInteger, UIViewAnimationTransition) {
    UIViewAnimationTransitionNone,
    UIViewAnimationTransitionFlipFromLeft,
    UIViewAnimationTransitionFlipFromRight,
    UIViewAnimationTransitionCurlUp,
    UIViewAnimationTransitionCurlDown,
};

* NS_OPTION:
typedef NS_OPTIONS(NSUInteger, UIViewAutoresizing) {
    UIViewAutoresizingNone                 = 0,
    UIViewAutoresizingFlexibleLeftMargin   = 1 << 0,
    UIViewAutoresizingFlexibleWidth        = 1 << 1,
    UIViewAutoresizingFlexibleRightMargin  = 1 << 2,
    UIViewAutoresizingFlexibleTopMargin    = 1 << 3,
    UIViewAutoresizingFlexibleHeight       = 1 << 4,
    UIViewAutoresizingFlexibleBottomMargin = 1 << 5
};

**Comment by jacktasia** [comment]
Sorry for the delay in getting this added. Should be available via MELPA within the next few hours. Please let me know if you have any feedback. Thanks!
