### ISSUE TITLE
Matlab Support ?

### ISSUE THREAD

**Issue by proudot** [jacktasia/dumb-jump#288]
Hi there, 
I love the idea of Dumb-Jump, Matlab compatibility is the only thing preventing me to use emacs for coding in Matlab. I currently use Sublime Text which is impressive when it comes to finding function AND methods, even if the methods as multiple implementation. I feel like Dumb-Jump has the capacities to do it, but it does not find definition for now. 

I am happy to help in testing/implementing/specifying some stuff, even though I am new to elips in general.

**Comment by jacktasia** [comment]
Thanks for opening this! I'll take a closer look at Matlab after work, but it should be pretty easier for me to add at least basic support for Matlab.

**Comment by jacktasia** [comment]
Looking at https://www.mathworks.com/help/matlab/ref/function.html it's pretty easy for me to support matlab. One small issue is that `m` is the file extension for matlab and it's also used for Objective-C. Since this is the first time there's been a conflict on file extensions I have to refactor the auto language detection part a bit.

**Comment by jacktasia** [comment]
I added basic support in #289 based on https://www.mathworks.com/help/matlab/ref/function.html. The change should be available via MELPA within 12 hours. Please let me know if you have any more suggestions.

**Comment by proudot** [comment]
Hi Jack, thanks a ton, I will test it ASAP (away from emacs atm).

**Comment by proudot** [comment]
It works great, thank you so much ! This is life changing. Thanks for being so quick as well, truly amazing!

**Comment by jacktasia** [comment]
@proudot  Awesome, thanks for letting me know!
