### ISSUE TITLE
Add C++ support

### ISSUE THREAD

**Issue by astoeckley** [jacktasia/dumb-jump#29]
Would love to try this plugin on C++!

**Comment by jacktasia** [comment]
Thanks for opening this. I definitely want to support C++. I just don't have much experience with it. You may want to follow this PR: https://github.com/jacktasia/dumb-jump/pull/20 If his fork works for you with `ag` then I'll prioritize the plan I mention there.

**Comment by rubikitch** [comment]
FYI, check out `exuberant-ctags` and browse `c.c`.
This file supports C/C++/C#/Java/Vera.
