### ISSUE TITLE
Reuse existing ignore files

### ISSUE THREAD

**Issue by DamienCassou** [jacktasia/dumb-jump#293]
My project already have .gitignore and .ignore files. Could dumb-jump reuse those?

**Comment by jacktasia** [comment]
This should be builtin to the searchers themselves. My understanding is that `git-grep`, `ag`, and `ripgrep` provide this functionality by default. If you're seeing something different can you please provide an example?

**Comment by DamienCassou** [comment]
Maybe the documentation could have a line or two about this? I'm closing for now and will reopen if I have more to say. Thank you for your answer.
