### ISSUE TITLE
question: why not TAGS?

### ISSUE THREAD

**Issue by omouse** [jacktasia/dumb-jump#30]
it would be helpful to me to know why I should use dumb-jump instead of TAGS. Personally, I generated TAGS files but what was missing was I couldn't just jump to the definition of a Rails function or the class that I was using in a Node project.

It might be helpful for others to compare and contrast the difference between using TAGS and dumb-jump.

**Comment by jacktasia** [comment]
My understanding is that TAGS takes a non trivial amount of time to setup for a project and it needs to stay up-to-date. So for this reason TAGS was never an attractive option for me. I wanted something with basic functionality that "just worked" for new projects.

If I am wrong about the above -- or it doesn't apply to you -- and you're happy with TAGS then I am not sure there's any advantage to using dumb-jump.
