### ISSUE TITLE
Error: https://stable.melpa.org/packages/dash-2.13.0.el: Not found

### ISSUE THREAD

**Issue by avatar-lavventura** [jacktasia/dumb-jump#302]
When I try to install the package I am getting the following error:

`https://stable.melpa.org/packages/dash-2.13.0.el: Not found`

**[Q]** How could I fix this error?

**Comment by jacktasia** [comment]
It sounds like your package list might be out of date. Try running `(package-list-packages)`

**Comment by avatar-lavventura** [comment]
Which also generates the following error:

```
Failed to verify signature archive-contents.sig:
No public key for 066DAFCB81E42C40 created at 2019-10-09T12:10:03+0300 using RSA
Command output:
gpg: Signature made Wed 09 Oct 2019 12:10:03 PM +03
gpg:                using RSA key C433554766D3DDC64221BFAA066DAFCB81E42C40
gpg: Can't check signature: No public key
```

**Comment by jacktasia** [comment]
https://stackoverflow.com/questions/58202993/emacs-failed-to-verify-signature-archive-contents-sig
