### ISSUE TITLE
Missing LICENSE or COPYING

### ISSUE THREAD

**Issue by omouse** [jacktasia/dumb-jump#31]
GPL v3 license? or MIT or?

**Comment by jacktasia** [comment]
Good question. I am leaning towards MIT, but I am open to suggestions. Do you have any particular thoughts on this?

**Comment by redshirtrob** [comment]
GPLv3. While I see the allure of releasing under MIT/BSD/Apache for libraries and frameworks that may get embedded in larger projects, I don't think that's likely for Emacs packages. 

In these cases, I lean towards the platform's preferred license.

**Comment by jacktasia** [comment]
@redshirtrob That makes sense to me. Done. Thanks!
