### ISSUE TITLE
Could not find rules for .F files

### ISSUE THREAD

**Issue by espenfl** [jacktasia/dumb-jump#313]
I have been using hotkeys when working in Python and that is convenient. From time to time I also do Fortran and found this plugin. Thanks for the work preparing this.

However, when I try this on a git repo'ed Fortran code I get:

`Could not find rules for ’.F file’`

By enabling the debugging I can see that `git grep` returns what it finds. After that it just ends with 

`DUMB JUMP DEBUG ‘dumb-jump-run-command‘ (FALLBACK) END`

What would be the next step trying to figure out what is not right?

I am on Emacs 26.2 with`f90-mode` enabled.

**Comment by jacktasia** [comment]
Thanks for opening this. So these Fortran files have uppercase `f` extensions (`.F` not `.f`)?

**Comment by espenfl** [comment]
Yes, all are `.F` in `f90` style.

**Comment by jacktasia** [comment]
Can you check if running this `(add-to-list 'dumb-jump-language-file-exts '(:language "fortran" :ext "F" :agtype "fortran" :rgtype "fortran"))` fixes it for you? If so, I'll add it to the code. If not, it's something else and I'll dig in more

**Comment by espenfl** [comment]
Thanks for the quick response. I get:
```
Warning (initialization): An error occurred while loading ‘/home/espenfl/.emacs.d/init.el’:

Symbol's value as variable is void: dumb-jump-language-file-exts
```
when I load this

**Comment by jacktasia** [comment]
Run it in a scratch buffer after dumb-jump has been loaded. Then try to jump again

**Comment by espenfl** [comment]
Aha, loading it with `M-:` worked. Complains that I should use `rg`, but that is something else. Is there a way to force `rg` when in git repo? Docs was a bit unclear and it seems if I set the force, `git grep` is still used.

**Comment by jacktasia** [comment]
`(setq dumb-jump-force-searcher 'rg)` should always work.

> Docs was a bit unclear and it seems if I set the force, git grep is still used.

Please expand on what is unclear. If you use the snippet above it should always use `rg`

**Comment by espenfl** [comment]
Thanks a lot for this fix. Yes, indeed, docs are clear enough when I read it again.

**Comment by jacktasia** [comment]
Awesome, happy to help. Added the new extension here e088ef3
