### ISSUE TITLE
Add C# support

### ISSUE THREAD

**Issue by ecuzzillo** [jacktasia/dumb-jump#32]
Would use it if it had it.

**Comment by jacktasia** [comment]
Thanks for opening this. I don't really have any C# experience. Is there a good C# project I should test against?

**Comment by ecuzzillo** [comment]
Well I work at Unity and want to use it on the Unity engine itself, which is huge and proprietary, but also most Unity projects use C#.

**Comment by ecuzzillo** [comment]
Maybe use one of the example projects?

**Comment by jacktasia** [comment]
@ecuzzillo Dumb Jump with support for C# is now available on MELPA. Please let me know if you have any feedback/issues. Thanks!
