### ISSUE TITLE
Groovy mode doesn't work

### ISSUE THREAD

**Issue by squarepegsys** [jacktasia/dumb-jump#320]
Almost a duplicate of #274 

I have a line that looks like:
```StringCalc calc = new StringCalc()```

And when i try to jump from the `StringCalc()` entry I get:

```’StringCalc’ groovy  declaration not found.```

I looked the .el file and it seems that the Groovy definitions are more like C# than they are like Java. Or maybe I don't understand the how it works.

You can play around with my sample project here.
https://github.com/squarepegsys/mh-string-calc-kata

**Comment by jacktasia** [comment]
Thanks for opening this! The sample project is super helpful for debugging. I do see an issue here, which I have a fix for, but can you please let me know what searcher you're using? Is it `ag` Thanks!

**Comment by squarepegsys** [comment]
Yep it's ag

**Comment by jacktasia** [comment]
Cool, thanks for letting me know. Then should be fixed in #321. I just merged it, so it may take a few hours to make its way to MELPA.

Thanks again for the report and example! If you get a chance to confirm the fix works for you, I'd appreciate it.

**Comment by squarepegsys** [comment]
Wow thanks for fixing it so fast! And the new version is in MELPA and it works great!

Thanks again!

**Comment by jacktasia** [comment]
Thanks for confirming and again for making it easy for me with the example repo!
