### ISSUE TITLE
Add dumb-jump-before-jump-hook

### ISSUE THREAD

**Issue by srustamo** [jacktasia/dumb-jump#338]
In 'evil-mode', jumping to a definition with `dumb-jump`  does not update the the jumplist. This breaks `C-o` (standard vim and evil command to go back to a previous point location).

I understand that there's dumb-jump-back, but that adds an unnecessary cognitive overhead.

One way of achieving this is: 
```
(advice-add 'dumb-jump-go :before (lambda (&rest r) (evil-set-jump)))
```
(https://github.com/jacktasia/dumb-jump/issues/80#issuecomment-242415785)

But adding a hook would be a cleaner solution.

**Comment by b3n** [comment]
Just a quick note on Evil: evil-mode already has `evil-goto-definition` (bound to `gd`), and the correct way to extend it is to add dumb-jump to `evil-goto-definition-functions`. If added as the first element of that list, it will try dumb-jump first, before falling back to the typical functions, and for free you'll get the jumplist set as expected.

**Comment by srustamo** [comment]
> ...evil-mode already has `evil-goto-definition` (bound to `gd`), and the correct way to extend it is to add dumb-jump to `evil-goto-definition-functions`..|

True. But dumb-jump already provides ‘before’ hook, and adding ‘after’ hook would add symmetry and a useful user option.

**Comment by jacktasia** [comment]
Just merged a PR for this. Please let me know if you have any feedback. Thanks!
