### ISSUE TITLE
Always received the "Took more than 2 seconds to find ..." until I ...

### ISSUE THREAD

**Issue by markskayff** [jacktasia/dumb-jump#340]
Just found this nice emacs extension you wrote for jumping to function declarations.

Installed it with Melpa in no time. Read the docs and started testing it.

So, I have helm installed so found the commands quickly and start playing with them. So, first thing I see is I get the message "Took more than 2 seconds to find <function-definition> .. please instal ag, rg or have your .dumpjump ingore file installed ..." 

So first thing I do is install "ag" in my local and remote systems (I use emacs for virtual machines too). After doing this and reinitializing emacs it kept on giving me the message. 

So, I went for the .dumbjump exclusions file solution. Again it kept sending the 2s message. 

So, I kept reading on the docs and found this:  (setq dumb-jump-force-searcher 'rg)

So, I explicitly added (setq dumb-jump-force-searcher 'ag) to my .emacs

And then it started working.

It would be good if you can mention this in the docs. As it'd probably use another searcher by default, like git-grep or something, and that won't be performant for your project.

**Comment by jacktasia** [comment]
I am not sure exactly what you're suggesting I should add to the documentation. It seems like you found the solution for yourself. The vast majority of the time `ag` and `rg` should behave similarly but it seems like there's something about your project where that's not the case and `rg` is significantly faster for you. Personally I find `rg` harder to work with in general with the way they handle their builds and distribution,  but some people seem to like it so it's supported. 

I'd happily consider a PR to update the `README` if you think it could be improved. Thanks!

**Comment by markskayff** [comment]
OK, thanks for the response. It was `ag` the on that worked well in the end.

I'd try a PR to the README if I can come up with something clear. Thanks!
