### ISSUE TITLE
Manually set project root

### ISSUE THREAD

**Issue by cweiske** [jacktasia/dumb-jump#36]
dumb-jump uses the first project root indicator file it finds to set the project root to its containing directory.

This approach does not work for complex projects in which multiple git checkouts are used:

```
php-typo3-project/
+ typo3conf/
|  + ext/
|     + extension/
|        + .gitignore
|     + extension2/
|        + .gitignore
+ typo3_src/
+ .gitignore
```

When using `dumb-jump` on a file in `php-typo3-project/typo3conf/ext/extension/src/Foo.php`, it finds `php-typo3-project/typo3conf/ext/extension/` as project root.
I'd rather want to have `php-typo3-project` as root.

**Comment by jacktasia** [comment]
Thanks for opening this. This is a great point. I will take a look at this over the weekend.

I think the easiest solution would be if we had a file called like `.dumbjumpignore` that was put in every directory that could mistakenly be treated as the project root. Any thoughts or concerns with this?

**Comment by cweiske** [comment]
Thank you! I'll wait for the next melpa release to try it out.
