### ISSUE TITLE
Incomplete results when using xref backend

### ISSUE THREAD

**Issue by dpassen** [jacktasia/dumb-jump#362]
When I use the deprecated command, `dumb-jump-go` I see a full list of possible candidates. When using the xref backend, `xref-find-definitions` provides an incomplete list. Is it possible I've misconfigured something or do they find a different symbol at point? I'm using emacs 27.1 and dumb-jump 20200808.1602.

`dumb-jump-go`
<img width="848" alt="Screen Shot 2020-08-14 at 4 02 06 PM" src="https://user-images.githubusercontent.com/997822/90292677-fef90b80-de47-11ea-8eee-b95fd202ed10.png">

`xref-find-definitions`
<img width="848" alt="Screen Shot 2020-08-14 at 4 03 17 PM" src="https://user-images.githubusercontent.com/997822/90292683-01f3fc00-de48-11ea-9d43-e5d23a8818a2.png">

**Comment by phikal** [comment]
I'm not a Clojure expert, so I don't know if these suggestions are all related. But this might be an issue related to `dumb-jump-process-symbol-by-lang` not working correctly.

**Comment by jacktasia** [comment]
Please let me know if this isn't fixed and we'll reopen. Thanks!
