### ISSUE TITLE
"Symbol's function definition is void: s-matched-positions-all"

### ISSUE THREAD

**Issue by cweiske** [jacktasia/dumb-jump#37]
> Symbol's function definition is void: s-matched-positions-all

I'm getting this error when running `dumb-jump-go` on a PHP function.
What does it mean?

----

ubuntu linux 16.04, emacs 24.5.1, dumb-jump 0.3.9

**Comment by poppingtonic** [comment]
@cweiske It seems that you need a package called [`s`](https://github.com/magnars/s.el). However, after running `C-M-g` on a Python function call, I still get the same issue. I deleted dumb-jump, installed `s`, then reinstalled dumb-jump, by running `M-x package-list-packages` and selecting the latest versions of each. I still get this problem. I'm running Ubuntu 14.04, and emacs 24.5.1, and dumb-jump 0.3.9.

**Comment by jacktasia** [comment]
@cweiske @poppingtonic `s-matched-positions-all` is a rather new addition to `s`. So you almost certainly have an old version of `s` loading. 

You can upgrade your packages (and remove old versions) by doing `M-x` `package-list-packages` then pressing `U` (Shift-u to make packages for upgrade) then pressing `x` (to actually start the upgrade) and then following the prompts it gives you. Should be `y` to upgrade and then `y` later to remove the old versions.

Or It may make sense to kill all versions of `s` in your `~/.emacs.d/elpa` folder and re-install it.

**Comment by jacktasia** [comment]
Please re-open this issue, or make a new comment here, if the solution I mentioned above does not work for you. Thanks!
