### ISSUE TITLE
How can I remap next/previous selection with dumb-jump-go?

### ISSUE THREAD

**Issue by NicholasBHubbard** [jacktasia/dumb-jump#384]
The default keys for next and previous selection are "C-n" and "C-p". How do I remap these keys?

**Comment by phikal** [comment]
`dumb-jump-go` uses [popup.el](https://github.com/auto-complete/popup-el/) to present the suggestions, so modifying [popup-menu-keymap](https://github.com/auto-complete/popup-el/blob/master/popup.el#L1289) to do what you want would probably be easiest way to change this.

That being said, you can also take a look at [dumb-jump-selector](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L78) to influence how `dumb-jump-go` presents it's solutions, or consider taking at look at the [xref interface](https://github.com/jacktasia/dumb-jump#basic), as `dumb-jump-go` is kind of deprecated.

**Comment by NicholasBHubbard** [comment]
thanks phikal I have everything working nicely now.
