### ISSUE TITLE
Add 'selectrum' to dumb-jump-selector 

### ISSUE THREAD

**Issue by marcora** [jacktasia/dumb-jump#385]
It would be great if you could add [selectrum](https://github.com/raxod502/selectrum) to the list of packages supported by the `dumb-jump-selector` function.

**Comment by phikal** [comment]
From what I understand, "selectrum" is a alternative completing-read implementation, so setting it to `completing-read` should do the job.

**Comment by marcora** [comment]
It works! Thnx
