### ISSUE TITLE
Changing the project

### ISSUE THREAD

**Issue by suntong** [jacktasia/dumb-jump#397]
Trying to understand how to change the project to limit the search, but I'm still not very clear after done a lot of readings, e.g.:

> - dumb-jump [knows the project root](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L813).
> - `(setq dumb-jump-default-project "~/code")` to change default project if one is not found (defaults to ~)

So, 

- how exactly dumb-jump [knows the project root](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L813)? As that link is now pointing to something irrelevant in my view.
- If my git repo contains lots of small projects within their own folders, it is possible to choose the project to limit the search with?

thx

**Comment by phikal** [comment]
I'm not sure what you are quoting, but my guess is that the link is just outdated, and might have been intended to point [here](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L1713).

The easiest way is to probably just create a `.dumbjump` file in the directory you wish to restrict searching to the particular tree, or any of the other files listed in `dumb-jump-project-denoters`. If that is not possible, maybe a [directory local value](https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Local-Variables.html) could be useful?

**Comment by suntong** [comment]
the link is indeed outdated, here is the Permanente one:

https://github.com/jacktasia/dumb-jump/blob/8f70acbe164553b225476fed55019ecddcf0bbd6/dumb-jump.el#L1713-L1715

Creating a `.dumbjump` file seems like a perfect solution. thx @phikal.
