### ISSUE TITLE
dumb-jump-go doesn't jump to definition even though there is only 1 result in dumb-jump-selector

### ISSUE THREAD

**Issue by shaunvxc** [jacktasia/dumb-jump#406]
I'm noticing some strange behavior when using `dumb-jump-go`

Per the below image, when I try to `dumb-jump-go` to `sv-pkgs`, instead of jumping to the module, it instead renders the `selector` (despite it  showing only 1 result).   I would expect this only in the case where there are multiple candidates.

![image](https://user-images.githubusercontent.com/3979753/137160068-4c714035-ec12-4c11-b93b-30f7b2ad1780.png)

Strangely, this behavior is inconsistent.  For example, when I `dumb-jump-go` to the `sv-magit` module (2 lines below), it behaves as I expect.

Apologies in advance if this is something that has been documented/resolved in the past.  I did some searching through the issues and couldn't find anything like it.

**Comment by phikal** [comment]
Out of curiosity, does the same issue also occur with when using xref?
