### ISSUE TITLE
xref jump fails on Tramp opened files

### ISSUE THREAD

**Issue by TrunovS** [jacktasia/dumb-jump#413]
I observe some strange behavior with ```xref``` backend which doesn't shows with obsolete ```dumb-jump-go```.
When working over Tramp, through ```xref```, jump to candidate goes in context of local machine, and opening local buffer as no such file exists.
The same jump to candidate through obsolete ```dumb-jump-go``` works just fine.
```xref-file-name-display``` has no power here too: project-relative, abs

**Comment by 404cn** [comment]
Same issue here, when I use xref to jump to def it jump to local dir and it does not exist, and emacs say

`Use M-x make-directory RET RET to create the directory and its parents`

**Comment by gsingh93** [comment]
This patch fixes this issue for me: https://github.com/jacktasia/dumb-jump/pull/432
