### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by ertpoi** [jacktasia/dumb-jump#422]
I am just starting to use this package and can't quite figure out how to `M .` in my project to get to some definition points.
Does this need to have TAGS for the project, meaning having run e.g. `etags` in all files and dirs of my project?
Thank you!
(lable would be question)

**Comment by jacktasia** [comment]
You definitely don't need to do anything with tags, as not having to is pretty much the point of this project. I recommend you read the README and ask any specific questions you may have after that.
