### ISSUE TITLE
Want to jump to method definition but getting all variables as results [PHP]

### ISSUE THREAD

**Issue by ryanwinchester** [jacktasia/dumb-jump#51]
### Using PHP

- It would be nice if methods and variables were not mixed in search results.
- It would also be nice to jump to the method definition if using C-M-g on a method usage.

I don't know, but maybe it could include open parentheses and `$` in regex (or whatever is used to search) to distinguish methods from variables?

Also searching for `usage` vs `definition` would be pretty cool.

e.g.

if the cursor is on fooBar() **usage** (i.e. `->fooBar(`) search for fooBar() **definition** (`function fooBar(`) and if cursor is on the **definition**, search for **usages**?

**Image -- cursor on method usage but getting variables as results:**

![dumb-jump](https://s3.amazonaws.com/f.cl.ly/items/2B0k1C3a3r1o3F1v1q0n/Screen%20Shot%202016-06-08%20at%207.43.56%20PM.png)

**Comment by jacktasia** [comment]
Thanks for reporting this! I think this should be pretty easy to (mostly) fix by [defining some language contexts](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L367) for PHP. I'll try to add in some for PHP tonight or tomorrow.

**Comment by jacktasia** [comment]
@ryanwinchester 

In the short term adding this to your config should improve finding PHP functions depending on the context:
```
(add-to-list 'dumb-jump-language-contexts
             '(:language "php" :type "function" :right "^(" :left nil))
```

If you run into other cases, please report back here and I will try to handle them too. I will add at least this one to the next release.

> Also searching for usage vs definition would be pretty cool.

It's certainly something I would like to support, but it would probably require another set of rules for each language.  Please make a new issue for it if it's something you'd like me to prioritize. Thanks!

**Comment by ryanwinchester** [comment]
Works way better:

![](https://s3-us-west-2.amazonaws.com/ryanwinchester/screenshots/dumb-jump-method.gif)

**Comment by jacktasia** [comment]
Awesome! Thanks for the update. Please let me know if you run into any other context issues like this.

**Comment by jacktasia** [comment]
@ryanwinchester If you don't mind me asking: what are you using to make the GIF you have above?

**Comment by ryanwinchester** [comment]
@jacktasia [LICEcap](http://www.cockos.com/licecap/)

**Comment by jacktasia** [comment]
@ryanwinchester Awesome, thanks!
