### ISSUE TITLE
Not usable in shell

### ISSUE THREAD

**Issue by zenspider** [jacktasia/dumb-jump#55]
I'll often be investigating things inside an emacs shell. Either running tests or grepping around or whatever. From there I'd like to be able to put point on a symbol and invoke dumb-jump. But because the buffer is in shell-mode, it fails out. It'd be nice to be able to set a "default language" or something to let it at least attempt a jump.

**Comment by jacktasia** [comment]
Thanks for the report. So we also need to know the project directory to search. One idea would be if a buffer is `*eshell*`(?) we somehow deduce the project path (via `cwd`?) and either get the language from the `.dumbjump` file in that project dir or by prompting the user with a list of languages. Thoughts?

**Comment by zenspider** [comment]
On July 1, 2016 at 11:36:39, Jack Angers (notifications@github.com) wrote:
> Thanks for the report. So we also need to know the project directory to search. One idea  
> would be if a buffer is `*eshell*`(?) we somehow deduce the project path (via `cwd`?)  
> and either get the language from the `.dumbjump` file in that project dir or by prompting  
> the user with a list of languages. Thoughts?


I use regular `M-x shell`, not eshell. But you can always use `default-directory` no matter what shell / buffer / mode you’re in.

**Comment by jacktasia** [comment]
Great point. I've thought this over a bit, and I think I can add support for this pretty easily. I will try to get something working over the weekend.

I am thinking of trying to determine the programming language automatically by the contents of the shell buffer, because if you're jumping from like a stacktrace, it will almost certainly reference files with their extension.

**Comment by zenspider** [comment]
I would be happy to put something in a directory local variable too.

**Comment by jacktasia** [comment]
@zenspider This should be available via MELPA now. Please open a new issue if you have any issues or  have other ideas. Thanks again!

**Comment by jacktasia** [comment]
@zenspider Have you had a chance to try this yet? I am curious if it works well for you or not. Thanks.
