### ISSUE TITLE
Fall back to symbol search.

### ISSUE THREAD

**Issue by rubikitch** [jacktasia/dumb-jump#63]
I use your dumb-jump and very happy with it!
But sometimes dumb-jump cannot find definitions, for example, functions defined by DSL.
In Emacs Lisp, dumb-jump cannot find `dumb-jump-mode` because it is defined by `define-minor-mode`.

```
;; Code in the dumb-jump repository.
(defun a ()
  (dumb-jump-mode)  ; NG
  (dumb-jump-go))   ; ok
```

I propose that dumb-jump should fall back to symbol search if it cannot find definitions.
Although dumb-jump produces many candidates in popup-menu, but I think it is more happy than "not found" because it is rare case.

For me, I use `find-function` to find definitions in Emacs Lisp.
This code is only an example.
This case can occur in Ruby and so on.

**Comment by jacktasia** [comment]
Thanks for the message. This is a really good idea. It should also be pretty easy to implement. Give me a day or two and I'll see what I can do. Thanks again!

**Comment by jacktasia** [comment]
@rubikitch This is available via MELPA now. Please let me know if you have any feedback. Thanks again!

**Comment by rubikitch** [comment]
Thanks! It works fine.
I blogged it in Japanse.
http://rubikitch.com/2016/08/07/dumb-jump-update/
