### ISSUE TITLE
Add option to set search scope as the first parent dir containing a VCS settings directory

### ISSUE THREAD

**Issue by OldhamMade** [jacktasia/dumb-jump#64]
Setting `(setq dumb-limit-to-vcs-project t)` and "jumping" within a file would search back up the directory tree, looking within each parent directory successively for a VCS settings directory (e.g. `.git`, `.svn`, etc), until reaching the main project directory defined by `dumb-jump-default-project`. If such a settings directory is found, this directory would be used as the "project" directory when performing searches.

For example:

```
code/               # `dumb-jump-default-project`
└── my-project/     # expected project dir
    ├── .git/       # VCS dir identifying expected project dir
    ├── my-defs.py  # location of target definition
    └── my-app.py   # current buffer location
```

In this case, searching would be scoped to `my-project` because it contains a `.git` directory. Should the `.git` directory be removed, scoping would fall back to `code/` as set by `dumb-jump-default-project`.

**Comment by jacktasia** [comment]
Thanks for the message. Just to confirm I understand what you're saying. This proposed setting, when enabled, would use the shallowest VCS directory instead of the deepest? So right now as it walks up the tree, it stops and uses the first VCS directory it finds. In other words, you're saying it should keep going up until it finds `dump-jump-default-project` and use the last VCS directory it found?

**Comment by OldhamMade** [comment]
Sorry, let me clarify with another example:
```
code/                     # `dumb-jump-default-project`
└── Client A              
│   └── project-1/        # active project dir
│       ├── .git/         # VCS dir identifying *expected* project dir
│       ├── active.py     # current buffer location
│       └── defs.py       # location of target definition 'foobar'
└── Client B
    └── project-2/        # second project dir
        ├── .git/         # VS dir identifying project dir
        └── more-defs.py  # contains a second definition of 'foobar'
```
It would seem from your description that this is already the behaviour, that when jumping to `foobar`  in `defs.py` from `active.py` one should stay within `code/Client A/project-1`, but I'm occasionally jumping to `project-2/more-defs.py`.

I'll keep an eye on the behaviour and raise a separate bug if I can provide replication steps.

**Comment by netromdk** [comment]
This is possible using the new ".dumbjumpignore" files. have a look at https://github.com/jacktasia/dumb-jump/pull/106/commits/12c315f0419e3b4b21db674d6261eff277f86985 for more information.
