### ISSUE TITLE
Use region when there is a selection? 

### ISSUE THREAD

**Issue by indigoviolet** [jacktasia/dumb-jump#66]
http://ergoemacs.org/emacs/elisp_thing-at-point_problems.html

**Comment by jacktasia** [comment]
Interesting. Have you actually run into any problems because of this behavior? I have not and this is the first I've heard about it.

**Comment by jacktasia** [comment]
Can you provide a reproducible example of your issue? I don't follow. My guess is you want to jump based on the selection instead of what's under point, which may be a good idea if you had a good example. Thanks!

**Comment by indigoviolet** [comment]
Yeah, in Ruby code: if you have

```x = Foo::BAR```

and you want to visit the module or class `Foo`, `thing-at-point` will return the entire thing (at least it does for me). Using the selection is a nice escape hatch.

**Comment by jacktasia** [comment]
Gotcha, thanks for the example! I'll look into this shortly.

**Comment by jacktasia** [comment]
@indigoviolet #71 is now available via MELPA.
