### ISSUE TITLE
Add location to find-tag

### ISSUE THREAD

**Issue by seanfarley** [jacktasia/dumb-jump#67]
I can make a PR for this but wanted to check if I was overlooking a design choice. When I jump to a definition, I find myself typing `M-*` to jump back to my previous location. Is there a reason why you don't have `(ring-insert find-tag-marker-ring (point-marker))` in the jump-go function?

**Comment by jacktasia** [comment]
> Is there a reason why you don't have (ring-insert find-tag-marker-ring (point-marker)) in the jump-go function?

There is `dumb-jump-back` already although that won't help you with your muscle memory. I honestly didn't know about the marker system when I first made dumb-jump, and when I first learned about it, I was unclear what the best practices were.

I am open to the idea of adding it in if others agree. Although in the short term adding the code below to init file should provide the functionality you need immediately. 
```
(require 'ring)
(add-function :before (symbol-function 'dumb-jump-go) (lambda () (interactive) (ring-insert find-tag-marker-ring (point-marker))))
```

**Comment by seanfarley** [comment]
Yeah, that's effectively what I've done locally. I don't see any downside but I can live with the local monkey patch and see if there's any problems.

**Comment by jacktasia** [comment]
@seanfarley I looked into it further, and I think you're correct. So I went ahead and added it in. If you update via MELPA, you should be able to remove your local patch. Thanks for bringing this up!

**Comment by seanfarley** [comment]
Awesome, thanks!
