### ISSUE TITLE
completion/selection via ivy

### ISSUE THREAD

**Issue by wbolster** [jacktasia/dumb-jump#76]
it would be great if the jump options that `dumb-jump` discovered could be selected using `ivy` instead of the current pop-up. it would be great if it looks like a `swiper`-style or `counsel-ag` style selection.

perhaps @abo-abo would be so kind to leave a comment on how that is best achieved. does it need changes in `dumb-jump`? would a `counsel-dumb-jump` be a better option? if so, is `dumb-jump` structured correctly to provide `counsel` with the right information?

**Comment by jacktasia** [comment]
@wbolster Thanks for creating this issue. I am certainly open to supporting other selectors beyond just the pop-up.

As far [as I can tell ](http://oremacs.com/swiper/#api) I can just use `ivy-read`. So I'll probably make a `defcustom` of like `dumb-jump-selector` that defaults to `popup` but can be `ivy` (and possibly other things too). Does that sound correct @abo-abo?

Thanks guys!

**Comment by abo-abo** [comment]
> Does that sound correct @abo-abo?

Yes, sounds fine. Here's an example of `ivy-read` use:

```elisp
(defun test ()
  (interactive)
  (ivy-read "test: "
            '(("abc (1.txt)" "~/1.txt" 123)
              ("def (2.txt)" "~/2.txt" 1124))
            :action (lambda (x)
                      (message
                       "open file %s and goto-char %d"
                       (nth 1 x) (nth 2 x)))))
```

**Comment by wbolster** [comment]
awesome. ivy all teh things!!1

but this won't behave as a ag/grep style buffer, right? (on the fly visiting with `C-l` and so on.)

**Comment by abo-abo** [comment]
> but this won't behave as a ag/grep style buffer, right? (on the fly visiting with C-l and so on.)

It can behave as ag/grep, in fact like `counsel-ag` or `counsel-grep`. <kbd>C-M-n</kbd> and <kbd>C-l</kbd> work for these two and are easy to implement.

**Comment by zilongshanren** [comment]
+1 for this feature ❤️

**Comment by jacktasia** [comment]
@wbolster @zilongshanren This is working now, but may take a bit before MELPA picks it up. All you need to do is already have `ivy` installed and add `(setq dumb-jump-selector 'ivy)` to your config.

**Comment by jacktasia** [comment]
It's on MELPA now. Please let me know if you have any issues. Thanks!

**Comment by wbolster** [comment]
great work, thanks a lot
