### ISSUE TITLE
Unable to select jump location from dropdown menu

### ISSUE THREAD

**Issue by vmalloc** [jacktasia/dumb-jump#77]
When trying to jump to a symbol with multiple options, I get a dropdown menu, and am unable to choose any of the options (`RET` has no effect)...

Is this a known issue?

**Comment by jacktasia** [comment]
> Is this a known issue?

No. Thanks for reporting it. Do you have a public repo somewhere I can clone with a place to jump from that shows this problem?  I have been unable to reproduce this so far. Thanks!

**Comment by vmalloc** [comment]
Sure - you can clone my config (https://github.com/vmalloc/emacs), and run it from a clean 25.1.1 Emacs (I think it reproduces on 24.x as well, but not sure).

I believe any code with multiple jump targets would cause this.

**Comment by jacktasia** [comment]
I have never tried emacs 25, so that's possibly it, but can you give me any more details, like where/what you were trying to jump from?

**Comment by vmalloc** [comment]
I'm pretty sure it happened to me before I made the switch as well (I only switched a few weeks ago).

And once again, pretty much any project with a few candidates causes this.

For instance:
```
proj
+----one.py
+----two.py
+----main.py
```
where main.py is just:
```python
foo()
```
And the other two are:
```python
def foo():
    pass
```

**Comment by vmalloc** [comment]
In any case, you can reset the cloned repo to before commit 4cf8f8100130ce8e9e7a977d916e9cb364400163, and it should be compatible with 24.x...

**Comment by jacktasia** [comment]
So I can reproduce this with your emacs config only, but nothing seems to be obviously wrong (as far as an error message). The only thing I can think of is the keymap to select the popup item is somehow getting messed up. I am going to step back and work on #76 because I have a feeling that it will solve this problem and probably be your preferred way of selecting stuff  anyway (from using your config)

**Comment by vmalloc** [comment]
@jacktasia awesome. I'll be patient then. Thanks!

**Comment by jacktasia** [comment]
Ok. I have #76 merged in, and I tried it against your config, and it worked as expected with `ivy`. You just need to add `(setq dumb-jump-selector 'ivy)` to your config.

The dumb-jump repo is updated, but it may take up 12 hours for the updates to be available via MELPA.

**Comment by jacktasia** [comment]
It's updated on MELPA now. Please let me know if updating and adding the `(setq dumb-jump-selector 'ivy)` works for you too. Thanks!

**Comment by vmalloc** [comment]
@jacktasia works like a charm! Thanks!
