### ISSUE TITLE
open in other window

### ISSUE THREAD

**Issue by wbolster** [jacktasia/dumb-jump#80]
i would love a dumb jump command that opens the definition in another window, just like `find-file-other-window` and `switch-to-buffer-other-window`.

otherwise, rock on. :)

**Comment by jacktasia** [comment]
Thanks for suggesting this. It's a great idea! Not sure why I didn't think of doing this myself...anyway, I'll look into adding this within the next few days. Thanks again!

**Comment by wbolster** [comment]
what i said: rock on :)

**Comment by jacktasia** [comment]
@wbolster This is up on MELPA now. You can either use `dumb-jump-go-other-window` instead or add `(setq dumb-jump-window 'other)` to your config and use `dumb-jump-go` as usual.

**Comment by wbolster** [comment]
awesome, works fine.

and with this `:before: advice it even "integrates" with evil's jump system so i can easily move back:

```
(advice-add 'dumb-jump-go :before (lambda (&rest r) (evil-set-jump)))
```
