### ISSUE TITLE
http://melpa.org/packages/f-20160815.1253.el: Not Found

### ISSUE THREAD

**Issue by ecuzzillo** [jacktasia/dumb-jump#83]
I don't know if this is my fault or your fault, but I figured I'd ask.

**Comment by jacktasia** [comment]
That's an old version of `f`. You probably just need to update your package list: <kbd>M-x</kbd> `package-list-packages` or `package-refresh-contents` (the former should do the latter I believe)

**Comment by ecuzzillo** [comment]
That fixed it, thanks!
