### ISSUE TITLE
c++ jumps to slightly wrong location

### ISSUE THREAD

**Issue by hrehfeld** [jacktasia/dumb-jump#87]
❑ marks the cursor. ⬱ where it jumps. ⟵ where it should jump

from here:

```
    if(_adaptive && !pixContribs.ProcessPixelDone())
    {
      _extrapolateRadianceValid(pixContribs,hit);
      _process❑PixelOverlap(hit,hit.directIllum.data(), 
        1/*thrElevImage[idx]*/,pixContribs,GetOctree<TRecord>());
      pixContribs.SetProcessPixelDone();
    }
    break;
```

to here:

```
 // --------------------------------------------------------------------------
 //  CAdaptiveCaching::_processPixelOverlap()                                      ⬱ 
 // --------------------------------------------------------------------------
 template<class TRecord,class TContribArray>
 int
 CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit,                     ⟵ 
                                        const float *directIllum,
                                        const float  thresholdElevation,
                                        TContribArray &carray,
                                        CRCOctree<TRecord> *octree)
 {
```

**Comment by jacktasia** [comment]
Thanks for reporting this! I'll probably be adding in something that will ignore results that start with a comment character for that language, which should fix this problem.

**Comment by netromdk** [comment]
Any updates regarding this?

Thanks

**Comment by jacktasia** [comment]
Sorry, not really. I'd kind of forgotten about this because it seemed like such an edge case, but now that there's another reporter I'll bump the priority. @netromdk is this limited to c/c++ for you too? Thanks for the bump.

**Comment by netromdk** [comment]
I've not seen it in any of my elisp or c++ yet. But I tried using the code of the above, and it jumps as stated. However, I found that if you remove the parameter `CRCOctree<TRecord> *octree` it will work fine. So I think your regexp doesn't handle the templated parameters correctly in the search. Hope that helps.

**Comment by netromdk** [comment]
Remember to close this issue now as well. :)
