### ISSUE TITLE
add shell-script (bash) support

### ISSUE THREAD

**Issue by benzitohhh** [jacktasia/dumb-jump#88]
Hi there,

this is an amazing tool.

Would be great if there was also suppor for shell-script (i.e. bash).

Thanks!

Ben

**Comment by jacktasia** [comment]
Thanks for opening the issue. I'll take a look at adding bash support this weekend. It should be pretty easy.

**Comment by benzitohhh** [comment]
wow thanks for the speedy response - much appreciated.

**Comment by jacktasia** [comment]
@benzitohhh FYI This change is now available via MELPA. Please open another issue if you run into any problems. Thanks!

**Comment by benzitohhh** [comment]
@jacktasia Cool works great - gonna be using this all the time! Thanks again.
