### ISSUE TITLE
dumb-jump cannot be used with files whose extensions end in numbers

### ISSUE THREAD

**Issue by jschwab** [jacktasia/dumb-jump#92]
I am in the process of trying to add fortran support to dumb-jump.

The regular expressions in `dumb-jump-parse-response-line`, i.e.

    (s-split ":?[0-9]+:" resp-line)
    (s-match ":?\\([0-9]+\\):" resp-line)

don't correctly handle the case when the filename ends in a number.  Since the colon is optional, they confuse the file extension and the line number. 
 
In this case, the value of resp-line looks like `"/path/to/file.f90:1701:      subroutine test(foo)"`

**Comment by jacktasia** [comment]
> I am in the process of trying to add fortran support to dumb-jump.

Awesome!

> don't correctly handle the case when the filename ends in a number. Since the colon is optional, they confuse the file extension and the line number.

Should be fixed now. Please let me know if you run into anything else on your way.
