### ISSUE TITLE
Support for Coq language

### ISSUE THREAD

**Issue by josemachino** [jacktasia/dumb-jump#98]
Coq has a formal language to write mathematical definitions. But having dumb-jump to support .v files will help. Thanks

**Comment by jacktasia** [comment]
Thanks for opening the issue. I am open to supporting Coq, but I have zero experience with it.

What keywords are important?

As far as I can tell:

* `Variable`
* `Inductive`
* `Lemma`
* `Definition`
* `Hypothesis`
* `Theorem`
* `Fixpoint`

Anything else? 

Additionally, as far as I can tell the structure is always `Keyword X ` (where `Keyword` is a word in the list above, and `X` is what you would want to jump from/to. This correct?

**Comment by josemachino** [comment]
Hi thanks you for your support, yes it is correct, Also the keyword Module, CoInductive. Have a good weekend.

**Comment by jacktasia** [comment]
@josemachino Dump Jump with Coq support is now on MELPA. Sorry for taking so long to add this. I tested with @jwiegley's [category-theory](https://github.com/jwiegley/category-theory) and it seems to work well, but please let me know if you run into any issues or have any ideas for enhancements. Thanks!

**Comment by jwiegley** [comment]
@jacktasia Thanks, I'll definitely give this a try. :)

**Comment by jwiegley** [comment]
Seems to be working very well!

**Comment by jacktasia** [comment]
> Seems to be working very well!

Glad to hear it! Thanks for letting me know. Please don't hesitate to let me know of any issues or ideas for improvements going forward.
