### ISSUE TITLE
Please add a prefix to test-helper.el to avoid conflicts with 68 other packages

### ISSUE THREAD

**Issue by tarsius** [jacktasia/dumb-jump#99]
There exist at least 69 packages that contain a file named `test-helper.el` that also provides the feature `test-helper`.

This leads to issues for users who have at least two of these packages installed.  It is unlikely that such a user would be able to run the tests of all of those packages.  If the primary test file of one of those packages does `(require 'test-helper)`, then it is undefined which of the various `test-helper.el` files gets loaded.  Which it is, depends on the order of the `load-path`.

To avoid this conflicts, you should rename your `test-helper.el` to `<your-package>-test-helper.el` and adjust the feature accordingly.

Also don't forget to update the `require` form in your primary test file and/or update references to the library/feature elsewhere.  Also, if your primary test file is named something like `test.el`, then please consider renaming that too (same for any other utility elisp files your repositoroy may contain).

Thanks!

PS: This issue is a bit generic because I had to open 69 issues.

**Comment by tarsius** [comment]
I've been informed, that `ert-runner` automatically loads the `test-helper.el` file. So you should **not** rename that file. Instead please see [this issue](https://github.com/rejeep/ert-runner.el/issues/38), where I suggest that the `(provide 'test-helper)` should be dropped instead. Please accept my apologize for opening these issues prematurely.

**Comment by jacktasia** [comment]
> This leads to issues for users who have at least two of these packages installed.

I can't see how this would lead to issues if they're installing via a package manager since none of the test code (at least in dumb-jump's case, but clearly depends on the config) would even make it on the end user's system in the first place.

Closing for now, but feel free to open a new issue if there's something actionable.
